#!/usr/bin/env node
// Release-time pipeline for the prebuilt napi platform packages (#52), driven by
// @semantic-release/exec's prepareCmd: wait for the released commit's "Build Native" workflow
// run, download its artifacts, wrap each in a `code-gauge-<platform>` package, publish the
// platform packages, and inject them into the main package's optionalDependencies at the
// released version (only in the packed tarball — the committed package.json stays version-less,
// like the 0.0.0-semantically-released version field). Everything runs in the PREPARE phase on
// purpose: semantic-release pushes the release tag after prepare and before the publish
// plugins, so a failure here aborts the release before anything is tagged and a plain re-run
// recovers (recomputing the same version; already-published platform versions are verified
// against the local artifacts and skipped). Platform packages published by a release that later
// fails are harmless orphans.
//
// Auth: NPM_TOKEN (npm trusted publishing cannot create a package, so first publishes need a
// token); once every platform package exists on the registry and shares a maintainer with the
// main package, a tokenless run proceeds and relies on per-package trusted publishers. Until
// either holds, the pipeline skips with a warning instead of failing the main release, leaving
// optionalDependencies uninjected so the main package never references unpublished versions —
// installs then keep today's source-build fallback.

import { execFileSync } from 'node:child_process';
import { copyFileSync, existsSync, mkdirSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const packageRoot = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const registryUrl = 'https://registry.npmjs.org/';

// The platform-package suffixes follow the napi-rs naming convention the runtime loader and
// scripts/installNative.mjs already probe; `library` names match build-native.yml's artifacts.
const platformTargets = [
  {
    triple: 'x86_64-unknown-linux-gnu',
    suffix: 'linux-x64-gnu',
    os: 'linux',
    cpu: 'x64',
    libc: 'glibc',
    library: 'libcode_gauge_native.so',
  },
  {
    triple: 'aarch64-unknown-linux-gnu',
    suffix: 'linux-arm64-gnu',
    os: 'linux',
    cpu: 'arm64',
    libc: 'glibc',
    library: 'libcode_gauge_native.so',
  },
  {
    triple: 'x86_64-unknown-linux-musl',
    suffix: 'linux-x64-musl',
    os: 'linux',
    cpu: 'x64',
    libc: 'musl',
    library: 'libcode_gauge_native.so',
  },
  {
    triple: 'aarch64-unknown-linux-musl',
    suffix: 'linux-arm64-musl',
    os: 'linux',
    cpu: 'arm64',
    libc: 'musl',
    library: 'libcode_gauge_native.so',
  },
  {
    triple: 'x86_64-apple-darwin',
    suffix: 'darwin-x64',
    os: 'darwin',
    cpu: 'x64',
    library: 'libcode_gauge_native.dylib',
  },
  {
    triple: 'aarch64-apple-darwin',
    suffix: 'darwin-arm64',
    os: 'darwin',
    cpu: 'arm64',
    library: 'libcode_gauge_native.dylib',
  },
  {
    triple: 'x86_64-pc-windows-msvc',
    suffix: 'win32-x64-msvc',
    os: 'win32',
    cpu: 'x64',
    library: 'code_gauge_native.dll',
  },
];

const [mode, version] = process.argv.slice(2);
if (mode === 'prepare' && version) {
  await prepare(version);
} else {
  console.error('Usage: prepareNativePackages.mjs prepare <version>');
  process.exit(1);
}

async function prepare(newVersion) {
  if (!process.env.NPM_TOKEN && !(await allPlatformPackagesPublishable())) {
    console.warn(
      'Skipping the platform packages: NPM_TOKEN is not set and not every code-gauge-* platform ' +
        'package exists on registry.npmjs.org yet. Complete the bootstrap steps in ' +
        'https://github.com/WillBooster/code-gauge/issues/52 to enable prebuilt publishes.'
    );
    return;
  }

  const artifactsDirPath = path.join(packageRoot, '.tmp', 'native-artifacts');
  const packagesDirPath = path.join(packageRoot, '.tmp', 'npm-native');
  rmSync(artifactsDirPath, { recursive: true, force: true });
  rmSync(packagesDirPath, { recursive: true, force: true });
  mkdirSync(artifactsDirPath, { recursive: true });

  const runId = await waitForBuildNativeRun();
  execFileSync('gh', ['run', 'download', String(runId), '--dir', artifactsDirPath], { stdio: 'inherit' });

  // The binary distribution must carry the statically linked crates' attributions (generated by
  // build-native.yml's third-party-notices job) plus this project's own license files.
  const noticesPath = path.join(artifactsDirPath, 'third-party-notices', 'THIRD-PARTY-NOTICES.txt');
  if (!existsSync(noticesPath)) {
    throw new Error(`Missing THIRD-PARTY-NOTICES.txt artifact: ${noticesPath}`);
  }

  const mainPackageJson = JSON.parse(readFileSync(path.join(packageRoot, 'package.json'), 'utf8'));
  const packageDirPaths = [];
  for (const target of platformTargets) {
    const libraryPath = path.join(artifactsDirPath, `code-gauge-${target.triple}`, target.library);
    if (!existsSync(libraryPath) || statSync(libraryPath).size === 0) {
      throw new Error(`Missing or empty artifact for ${target.triple}: ${libraryPath}`);
    }
    const packageDirPath = path.join(packagesDirPath, `code-gauge-${target.suffix}`);
    mkdirSync(packageDirPath, { recursive: true });
    copyFileSync(libraryPath, path.join(packageDirPath, 'code-gauge.node'));
    copyFileSync(path.join(packageRoot, 'LICENSE'), path.join(packageDirPath, 'LICENSE'));
    copyFileSync(path.join(packageRoot, 'NOTICE'), path.join(packageDirPath, 'NOTICE'));
    copyFileSync(noticesPath, path.join(packageDirPath, 'THIRD-PARTY-NOTICES.txt'));
    writeFileSync(
      path.join(packageDirPath, 'package.json'),
      `${JSON.stringify(createPlatformPackageJson(target, newVersion, mainPackageJson), undefined, 2)}\n`
    );
    writeFileSync(
      path.join(packageDirPath, 'README.md'),
      `# code-gauge-${target.suffix}\n\nPrebuilt \`${target.triple}\` native addon for ` +
        `[code-gauge](https://www.npmjs.com/package/code-gauge). Install \`code-gauge\` instead of ` +
        `this package; installers pick it up automatically via optionalDependencies.\n`
    );
    packageDirPaths.push(packageDirPath);
  }

  // The token goes through npm's env-var expansion instead of being written to disk. Without a
  // token the userconfig line expands to empty, and npm's trusted-publishing OIDC exchange (which
  // runs unconditionally in GitHub Actions and overrides the userconfig token on success) takes
  // over, matching the bootstrap-then-OIDC plan.
  const userconfigPath = path.join(packagesDirPath, '.npmrc');
  // oxlint-disable-next-line no-template-curly-in-string -- npm expands the reference at run time.
  writeFileSync(userconfigPath, '//registry.npmjs.org/:_authToken=${NPM_TOKEN}\n');
  for (const packageDirPath of packageDirPaths) {
    await publishPlatformPackage(packageDirPath, newVersion, userconfigPath);
  }

  // Injected only after every platform publish succeeded, so the main package can never
  // reference an unpublished version.
  mainPackageJson.optionalDependencies = Object.fromEntries(
    platformTargets.map((target) => [`code-gauge-${target.suffix}`, newVersion])
  );
  writeFileSync(path.join(packageRoot, 'package.json'), `${JSON.stringify(mainPackageJson, undefined, 2)}\n`);
}

async function publishPlatformPackage(packageDirPath, newVersion, userconfigPath) {
  const packageName = path.basename(packageDirPath);
  // The deterministic local tarball integrity lets an already-published version be classified:
  // identical integrity means a previous (partially failed) run of THIS release published it and
  // it is safe to skip; anything else is a squatted or corrupted package that must never end up
  // referenced by optionalDependencies.
  const localIntegrity = JSON.parse(
    execFileSync('npm', ['pack', '--dry-run', '--json'], { cwd: packageDirPath, encoding: 'utf8' })
  )[0].integrity;
  const verifyPublished = async () => {
    const published = await fetchPackageVersion(packageName, newVersion);
    if (!published) return false;
    if (published.dist?.integrity !== localIntegrity) {
      // Distinguish our own earlier artifact from a foreign one before failing: a partially
      // failed release followed by another commit recomputes the SAME version from DIFFERENT
      // artifacts, and misdiagnosing that as squatting would send the operator down the wrong
      // path. Published versions are immutable either way, so both paths fail loudly with the
      // matching remedy instead of referencing a tarball this release did not produce.
      const mainMaintainers = maintainerNames(await fetchPackageDocument('code-gauge'));
      const isOurs = maintainerNames(await fetchPackageDocument(packageName)).some((maintainer) =>
        mainMaintainers.includes(maintainer)
      );
      throw new Error(
        isOurs
          ? `${packageName}@${newVersion} was already published (likely by an earlier partially ` +
              `failed release) from different artifacts (registry integrity ${published.dist?.integrity}, ` +
              `this release built ${localIntegrity}). Recover by re-running the release for the exact ` +
              'commit whose Build Native artifacts were published (the integrity then matches and the ' +
              'published versions are skipped), or by landing a commit with a HIGHER bump level than ' +
              'the failed release (no tag was pushed, so a same-level commit recomputes the same ' +
              'version). Unpublishing does not help: npm never allows republishing an already-used ' +
              'name and version combination.'
          : `${packageName}@${newVersion} already exists on the registry with integrity ` +
              `${published.dist?.integrity}, but this release built ${localIntegrity}, and the package ` +
              'shares no maintainer with code-gauge. Refusing to reference a tarball this release did ' +
              'not produce (name squatting); resolve ownership before enabling prebuilt publishes (#52).'
      );
    }
    console.warn(`Skipping ${packageName}@${newVersion}: already published with matching integrity.`);
    return true;
  };

  if (await verifyPublished()) return;
  const publishOnce = () =>
    execFileSync('npm', ['publish', '--userconfig', userconfigPath], {
      cwd: packageDirPath,
      stdio: 'inherit',
      env: { ...process.env, NPM_TOKEN: process.env.NPM_TOKEN ?? '' },
    });
  try {
    publishOnce();
  } catch {
    // The registry may have accepted the upload while the client saw an error (dropped response,
    // 5xx after commit), so re-check before retrying — a blind retry of the immutable
    // name/version would fail with EPUBLISHCONFLICT despite the desired state being reached.
    await sleep(10_000);
    if (await verifyPublished()) return;
    try {
      publishOnce();
    } catch (error) {
      await sleep(10_000);
      if (await verifyPublished()) return;
      throw error;
    }
  }
}

async function waitForBuildNativeRun() {
  // Build Native starts from the same push that triggered the release, so poll until a run for
  // this commit succeeds. Transient `gh` failures count as "not ready yet" — the deadline bounds
  // a persistently broken gh. Re-releases of old commits can outlive the 90-day artifact
  // retention; the download then fails loudly and the release must be re-run from a fresh build.
  const commitSha = requireEnv('GITHUB_SHA');
  const deadline = Date.now() + 45 * 60 * 1000;
  for (;;) {
    let runs;
    try {
      runs = JSON.parse(
        execFileSync(
          'gh',
          [
            'run',
            'list',
            '--workflow',
            'build-native.yml',
            '--commit',
            commitSha,
            '--json',
            'databaseId,status,conclusion',
          ],
          { encoding: 'utf8' }
        )
      );
    } catch (error) {
      console.warn(
        `Listing Build Native runs failed (${error instanceof Error ? error.message : String(error)}); retrying...`
      );
    }
    if (runs) {
      const succeeded = runs.find((run) => run.status === 'completed' && run.conclusion === 'success');
      if (succeeded) return succeeded.databaseId;
      // Only a state no waiting can fix fails fast: every run finished and none succeeded.
      if (runs.length > 0 && runs.every((run) => run.status === 'completed')) {
        throw new Error(
          `No successful Build Native run for ${commitSha} ` +
            `(conclusions: ${runs.map((run) => run.conclusion).join(', ')}). Re-run it for this ` +
            'commit with `gh run rerun <run-id>` and then re-run the release.'
        );
      }
    }
    if (Date.now() > deadline) {
      throw new Error(`Timed out waiting for a successful Build Native run for ${commitSha}`);
    }
    console.info(`Waiting for the Build Native run for ${commitSha}...`);
    await sleep(30_000);
  }
}

function createPlatformPackageJson(target, newVersion, mainPackageJson) {
  return {
    name: `code-gauge-${target.suffix}`,
    version: newVersion,
    description: `Prebuilt ${target.triple} native addon for code-gauge`,
    repository: mainPackageJson.repository,
    license: mainPackageJson.license,
    author: mainPackageJson.author,
    main: 'code-gauge.node',
    files: ['code-gauge.node', 'LICENSE', 'NOTICE', 'THIRD-PARTY-NOTICES.txt'],
    os: [target.os],
    cpu: [target.cpu],
    ...(target.libc ? { libc: [target.libc] } : {}),
    publishConfig: { access: 'public', registry: registryUrl },
  };
}

// The tokenless (post-bootstrap) gate. Mere registry existence must not enable the flow: anyone
// can claim an unscoped name, and treating a squatted package as "bootstrap done" would wire it
// into optionalDependencies. Every platform package must share a maintainer with the main
// package — an attacker cannot list one of our maintainers on their package.
async function allPlatformPackagesPublishable() {
  const mainMaintainers = maintainerNames(await fetchPackageDocument('code-gauge'));
  for (const target of platformTargets) {
    const name = `code-gauge-${target.suffix}`;
    const document = await fetchPackageDocument(name);
    if (!document) return false;
    if (!maintainerNames(document).some((maintainer) => mainMaintainers.includes(maintainer))) {
      throw new Error(
        `${name} exists on the registry but shares no maintainer with code-gauge — the name ` +
          'appears to be squatted. Resolve ownership before enabling prebuilt publishes (#52).'
      );
    }
  }
  return true;
}

function maintainerNames(document) {
  return (document?.maintainers ?? []).map((maintainer) => maintainer.name);
}

async function fetchPackageDocument(packageName) {
  return await fetchRegistryJson(`${registryUrl}${packageName}`);
}

async function fetchPackageVersion(packageName, packageVersion) {
  return await fetchRegistryJson(`${registryUrl}${packageName}/${encodeURIComponent(packageVersion)}`);
}

// undefined for 404; one retry for transient failures, then throw — nothing is tagged during
// prepare, so failing loudly keeps the release re-runnable instead of publishing a main package
// with silently missing prebuilds.
async function fetchRegistryJson(url, isRetry = false) {
  try {
    const response = await fetch(url);
    if (response.status === 404) return;
    if (!response.ok) throw new Error(`GET ${url} responded ${response.status}`);
    return await response.json();
  } catch (error) {
    if (isRetry) throw error;
    await sleep(5000);
    return await fetchRegistryJson(url, true);
  }
}

function sleep(milliseconds) {
  return new Promise((resolve) => setTimeout(resolve, milliseconds));
}

function requireEnv(name) {
  const value = process.env[name];
  if (!value) throw new Error(`${name} is not set`);
  return value;
}
