import type { LanguageName } from '../../src/index.js';

/**
 * Expected metrics for the real-world OSS corpus under test/fixtures/oss (famous open-source
 * files pinned to release tags; see test/fixtures/oss/README.md for provenance).
 *
 * The per-function complexity/NCSS oracle values were produced by major existing tools, NOT by
 * code-gauge itself, so these tests verify code-gauge against independent implementations:
 *
 * - `pmd` — PMD 7.26.0 (CyclomaticComplexity / CognitiveComplexity / NcssCount rules, report
 *   level 1), the engine whose semantics code-gauge's Java complexity deliberately follows.
 *   All 41 Java methods match on cyclomatic AND cognitive complexity; NCSS matches on 38.
 * - `lizard` — lizard 1.23.0 cyclomatic complexity (CCN). Its CCN semantics coincide with
 *   code-gauge's on every function it can attribute in C, C++, Go, and Java.
 * - `gocognit` — gocognit v1.2.0, the standard Go implementation of SonarSource cognitive
 *   complexity. 37 of 38 functions match.
 * - `complexipy` — complexipy 7.0.0, a Rust implementation of SonarSource cognitive complexity
 *   for Python. 23 of 28 functions match.
 * - `sonarjs` — eslint-plugin-sonarjs 0.25.1 (SonarSource's own ESLint port of cognitive
 *   complexity) on ESLint 8.57.0 / @typescript-eslint/parser 7.18.0. 57 functions match across
 *   JavaScript, TypeScript, JSX, and TSX.
 *
 * Line metrics in `aggregates` were verified against cloc 2.06 for all files (code/comment/blank
 * identical; code-gauge additionally counts the empty line after a trailing final newline as one
 * blank line, so `lines.total` and `lines.blank` are one higher than cloc's). Two files need a
 * different oracle:
 *
 * - Python: cloc classifies docstrings as comments while code-gauge (like tree-sitter) treats
 *   them as expression statements, i.e. code. For requests' sessions.py cloc reports
 *   code=413/comment=267; code-gauge reports code=564/comment=116 — the code+comment sum (680)
 *   is identical, and the 151-line delta is exactly the docstring lines.
 * - Rust: cloc misparses gitignore.rs because glob patterns such as "foo/**" + "/*" inside string
 *   literals look like block-comment openers to it. tokei 13.0 (Rust-aware) confirms code-gauge:
 *   code=562 for both; tokei's comment(165)+doc-comment-blank(29)=194 vs code-gauge's 193+blank
 *   split differs only in how blank lines inside doc comments are classified.
 *
 * `knownDivergences` pins every function where an oracle tool disagrees with code-gauge, so a
 * behavior change on either side of a documented gap fails loudly. The reasons:
 *
 * - pmd/ncss: PMD's NCSS visitor does not descend into expression positions (anonymous classes
 *   returned from methods), while code-gauge counts statement-shaped content uniformly — the same
 *   deliberate divergence documented in pmdParity.test.ts.
 * - gocognit/cognitive: gocognit charges SonarSource's +1 recursion increment (gin's `iterate`);
 *   code-gauge does not charge recursion.
 * - complexipy/cognitive: complexipy charges comprehensions and their internal `if`/`for` clauses;
 *   code-gauge counts only statement-level decisions (dialect difference among Sonar ports).
 * - sonarjs/cognitive: sonarjs attributes nested-closure content to the innermost enclosing
 *   function only, while code-gauge (like PMD) also attributes it to the enclosing declared
 *   function; a few remaining cases differ on JSX expressions, which sonarjs does not analyze.
 * - lizard/cyclomatic (jsx, ruby, rust): lizard does not parse JSX expression trees, Ruby
 *   modifier conditionals, or Rust `?`/match-arm constructs the way a real grammar does; the
 *   tree-sitter grammar sees strictly more (or more precise) structure.
 *
 * Aggregate float values (duplicationRatio, halstead.volume, maintainabilityIndex) are rounded
 * to 4 decimals by roundFloats() in ossMetrics.test.ts before comparison.
 *
 * Regeneration: the oracle capture procedure (tool versions, invocations, and join-by-start-line
 * logic) is described in the PR that introduced this file; expected values only change when the
 * measurer's semantics change, in which case the affected entries must be re-verified against the
 * tools above.
 */

export type OracleMetric = 'cyclomatic' | 'cognitive' | 'ncss';

/** [functionName, startLine, metric, tool, expectedValue] — code-gauge must equal expectedValue. */
export type OracleFunctionEntry = readonly [string, number, OracleMetric, string, number];

/**
 * [functionName, startLine, metric, tool, toolValue, codeGaugeValue] — code-gauge must equal
 * codeGaugeValue, which intentionally differs from toolValue (see file doc above). If an
 * implementation change makes code-gauge match the tool, move the entry to oracleFunctions.
 */
export type KnownDivergenceEntry = readonly [string, number, OracleMetric, string, number, number];

export interface OssAggregateExpectation {
  lines: { total: number; code: number; comment: number; blank: number };
  functionCount: number;
  classCount: number;
  cyclomaticComplexity: number;
  maxCyclomaticComplexity: number;
  cognitiveComplexity: number;
  maxCognitiveComplexity: number;
  nestingDepth: number;
  ncssCount: number;
  callGraph: Record<string, number>;
  coupling: Record<string, number>;
  syntaxFeatures: Record<string, number>;
  typeComplexity: Record<string, number>;
  duplication: Record<string, number>;
  halstead: Record<string, number>;
  maintainabilityIndex: number;
}

export interface OssFileExpectation {
  file: string;
  language: LanguageName;
  aggregates: OssAggregateExpectation;
  oracleFunctions: readonly OracleFunctionEntry[];
  knownDivergences: readonly KnownDivergenceEntry[];
}

export const ossExpectations: readonly OssFileExpectation[] = [
  {
    file: 'bitcoin-25.0-bech32.cpp',
    language: 'cpp',
    aggregates: {
      lines: {
        total: 570,
        code: 286,
        comment: 219,
        blank: 65,
      },
      functionCount: 13,
      classCount: 0,
      cyclomaticComplexity: 79,
      maxCyclomaticComplexity: 35,
      cognitiveComplexity: 149,
      maxCognitiveComplexity: 89,
      nestingDepth: 5,
      ncssCount: 240,
      callGraph: {
        callCount: 113,
        uniqueCalleeCount: 23,
        internalCallCount: 16,
        internalEdgeCount: 16,
        recursiveFunctionCount: 0,
        maxFanIn: 3,
        maxFanOut: 6,
        maxCallDepth: 2,
      },
      coupling: {
        importCount: 6,
        importSourceCount: 6,
        relativeImportCount: 0,
        externalImportCount: 6,
        exportCount: 0,
      },
      syntaxFeatures: {
        assignmentCount: 48,
        awaitExpressionCount: 0,
        loopStatementCount: 17,
        mutableBindingCount: 82,
        returnStatementCount: 25,
        throwStatementCount: 0,
        tryStatementCount: 0,
      },
      typeComplexity: {
        typeAnnotationCount: 0,
        typeAliasCount: 0,
        interfaceCount: 0,
        genericParameterCount: 0,
        unionTypeCount: 0,
        intersectionTypeCount: 0,
        conditionalTypeCount: 0,
        typeAssertionCount: 0,
        nonNullAssertionCount: 0,
        satisfiesExpressionCount: 0,
      },
      duplication: {
        duplicateBlockCount: 2,
        duplicateBlockGroupCount: 1,
        duplicateLineCount: 9,
        duplicationRatio: 0.0315,
        maxDuplicateBlockSize: 44,
      },
      halstead: {
        distinctOperators: 28,
        distinctOperands: 185,
        totalOperators: 571,
        totalOperands: 1089,
        volume: 12_839.618,
      },
      maintainabilityIndex: 7.0231,
    },
    oracleFunctions: [
      ['GenerateGFTables', 46, 'cyclomatic', 'lizard', 6],
      ['EncodingConstant', 122, 'cyclomatic', 'lizard', 3],
      ['PolyMod', 130, 'cyclomatic', 'lizard', 7],
      ['GenerateSyndromeConstants', 240, 'cyclomatic', 'lizard', 3],
      ['Syndrome', 261, 'cyclomatic', 'lizard', 3],
      ['LowerCase', 281, 'cyclomatic', 'lizard', 3],
      ['ExpandHRP', 312, 'cyclomatic', 'lizard', 2],
      ['Decode', 373, 'cyclomatic', 'lizard', 10],
      ['LocateErrors', 400, 'cyclomatic', 'lizard', 35],
    ],
    knownDivergences: [],
  },
  {
    file: 'express-4.18.2-response.js',
    language: 'javascript',
    aggregates: {
      lines: {
        total: 1170,
        code: 537,
        comment: 475,
        blank: 158,
      },
      functionCount: 42,
      classCount: 0,
      cyclomaticComplexity: 134,
      maxCyclomaticComplexity: 30,
      cognitiveComplexity: 187,
      maxCognitiveComplexity: 39,
      nestingDepth: 4,
      ncssCount: 428,
      callGraph: {
        callCount: 184,
        uniqueCalleeCount: 70,
        internalCallCount: 21,
        internalEdgeCount: 21,
        recursiveFunctionCount: 4,
        maxFanIn: 6,
        maxFanOut: 2,
        maxCallDepth: 5,
      },
      coupling: {
        importCount: 0,
        importSourceCount: 0,
        relativeImportCount: 0,
        externalImportCount: 0,
        exportCount: 0,
      },
      syntaxFeatures: {
        assignmentCount: 101,
        awaitExpressionCount: 0,
        loopStatementCount: 3,
        mutableBindingCount: 103,
        returnStatementCount: 41,
        throwStatementCount: 5,
        tryStatementCount: 0,
      },
      typeComplexity: {
        typeAnnotationCount: 0,
        typeAliasCount: 0,
        interfaceCount: 0,
        genericParameterCount: 0,
        unionTypeCount: 0,
        intersectionTypeCount: 0,
        conditionalTypeCount: 0,
        typeAssertionCount: 0,
        nonNullAssertionCount: 0,
        satisfiesExpressionCount: 0,
      },
      duplication: {
        duplicateBlockCount: 2,
        duplicateBlockGroupCount: 2,
        duplicateLineCount: 48,
        duplicationRatio: 0.0894,
        maxDuplicateBlockSize: 114,
      },
      halstead: {
        distinctOperators: 23,
        distinctOperands: 280,
        totalOperators: 673,
        totalOperands: 1321,
        volume: 16_436.8889,
      },
      maintainabilityIndex: 0,
    },
    oracleFunctions: [
      ['status', 67, 'cognitive', 'sonarjs', 3],
      ['send', 111, 'cognitive', 'sonarjs', 39],
      ['json', 250, 'cognitive', 'sonarjs', 5],
      ['jsonp', 293, 'cognitive', 'sonarjs', 11],
      ['sendStatus', 369, 'cognitive', 'sonarjs', 1],
      ['(anonymous)', 449, 'cognitive', 'sonarjs', 5],
      ['(anonymous)', 518, 'cognitive', 'sonarjs', 5],
      ['contentType', 619, 'cognitive', 'sonarjs', 1],
      ['(anonymous)', 684, 'cognitive', 'sonarjs', 4],
      ['attachment', 719, 'cognitive', 'sonarjs', 1],
      ['append', 744, 'cognitive', 'sonarjs', 6],
      ['header', 777, 'cognitive', 'sonarjs', 18],
      ['(anonymous)', 854, 'cognitive', 'sonarjs', 8],
      ['location', 906, 'cognitive', 'sonarjs', 2],
      ['redirect', 936, 'cognitive', 'sonarjs', 6],
      ['(anonymous)', 991, 'cognitive', 'sonarjs', 3],
      ['(anonymous)', 1033, 'cognitive', 'sonarjs', 1],
      ['onaborted', 1048, 'cognitive', 'sonarjs', 1],
      ['ondirectory', 1058, 'cognitive', 'sonarjs', 1],
      ['onerror', 1068, 'cognitive', 'sonarjs', 1],
      ['onend', 1075, 'cognitive', 'sonarjs', 1],
      ['(anonymous)', 1092, 'cognitive', 'sonarjs', 3],
      ['headers', 1118, 'cognitive', 'sonarjs', 1],
      ['(anonymous)', 1153, 'cognitive', 'sonarjs', 1],
    ],
    knownDivergences: [
      ['(anonymous)', 90, 'cognitive', 'sonarjs', 1, 2],
      ['sendFile', 419, 'cognitive', 'sonarjs', 5, 14],
      ['(anonymous)', 501, 'cognitive', 'sonarjs', 1, 10],
      ['download', 550, 'cognitive', 'sonarjs', 14, 15],
      ['render', 1016, 'cognitive', 'sonarjs', 2, 5],
      ['sendfile', 1043, 'cognitive', 'sonarjs', 1, 26],
      ['onfinish', 1087, 'cognitive', 'sonarjs', 4, 9],
      ['stringify', 1145, 'cognitive', 'sonarjs', 4, 7],
    ],
  },
  {
    file: 'gin-1.9.1-gin.go',
    language: 'go',
    aggregates: {
      lines: {
        total: 712,
        code: 487,
        comment: 122,
        blank: 103,
      },
      functionCount: 44,
      classCount: 0,
      cyclomaticComplexity: 61,
      maxCyclomaticComplexity: 18,
      cognitiveComplexity: 82,
      maxCognitiveComplexity: 30,
      nestingDepth: 3,
      ncssCount: 360,
      callGraph: {
        callCount: 158,
        uniqueCalleeCount: 82,
        internalCallCount: 40,
        internalEdgeCount: 40,
        recursiveFunctionCount: 3,
        maxFanIn: 5,
        maxFanOut: 3,
        maxCallDepth: 3,
      },
      coupling: {
        importCount: 13,
        importSourceCount: 13,
        relativeImportCount: 0,
        externalImportCount: 13,
        exportCount: 0,
      },
      syntaxFeatures: {
        assignmentCount: 102,
        awaitExpressionCount: 0,
        loopStatementCount: 7,
        mutableBindingCount: 7,
        returnStatementCount: 45,
        throwStatementCount: 0,
        tryStatementCount: 0,
      },
      typeComplexity: {
        typeAnnotationCount: 0,
        typeAliasCount: 0,
        interfaceCount: 0,
        genericParameterCount: 0,
        unionTypeCount: 0,
        intersectionTypeCount: 0,
        conditionalTypeCount: 0,
        typeAssertionCount: 0,
        nonNullAssertionCount: 0,
        satisfiesExpressionCount: 0,
      },
      duplication: {
        duplicateBlockCount: 0,
        duplicateBlockGroupCount: 0,
        duplicateLineCount: 0,
        duplicationRatio: 0,
        maxDuplicateBlockSize: 0,
      },
      halstead: {
        distinctOperators: 23,
        distinctOperands: 333,
        totalOperators: 553,
        totalOperands: 1300,
        volume: 15_705.534,
      },
      maintainabilityIndex: 3.7888,
    },
    oracleFunctions: [
      ['Last', 54, 'cognitive', 'gocognit', 1],
      ['Last', 54, 'cyclomatic', 'lizard', 2],
      ['New', 183, 'cognitive', 'gocognit', 0],
      ['New', 183, 'cyclomatic', 'lizard', 1],
      ['(anonymous)', 209, 'cyclomatic', 'lizard', 1],
      ['Default', 216, 'cognitive', 'gocognit', 0],
      ['Default', 216, 'cyclomatic', 'lizard', 1],
      ['Handler', 223, 'cognitive', 'gocognit', 1],
      ['Handler', 223, 'cyclomatic', 'lizard', 2],
      ['allocateContext', 232, 'cognitive', 'gocognit', 0],
      ['allocateContext', 232, 'cyclomatic', 'lizard', 1],
      ['Delims', 239, 'cognitive', 'gocognit', 0],
      ['SecureJsonPrefix', 245, 'cognitive', 'gocognit', 0],
      ['SecureJsonPrefix', 245, 'cyclomatic', 'lizard', 1],
      ['LoadHTMLGlob', 252, 'cognitive', 'gocognit', 1],
      ['LoadHTMLGlob', 252, 'cyclomatic', 'lizard', 2],
      ['LoadHTMLFiles', 268, 'cognitive', 'gocognit', 1],
      ['LoadHTMLFiles', 268, 'cyclomatic', 'lizard', 2],
      ['SetHTMLTemplate', 279, 'cognitive', 'gocognit', 1],
      ['SetHTMLTemplate', 279, 'cyclomatic', 'lizard', 2],
      ['SetFuncMap', 288, 'cognitive', 'gocognit', 0],
      ['SetFuncMap', 288, 'cyclomatic', 'lizard', 1],
      ['NoRoute', 293, 'cognitive', 'gocognit', 0],
      ['NoRoute', 293, 'cyclomatic', 'lizard', 1],
      ['NoMethod', 299, 'cognitive', 'gocognit', 0],
      ['NoMethod', 299, 'cyclomatic', 'lizard', 1],
      ['Use', 307, 'cognitive', 'gocognit', 0],
      ['Use', 307, 'cyclomatic', 'lizard', 1],
      ['rebuild404Handlers', 314, 'cognitive', 'gocognit', 0],
      ['rebuild404Handlers', 314, 'cyclomatic', 'lizard', 1],
      ['rebuild405Handlers', 318, 'cognitive', 'gocognit', 0],
      ['rebuild405Handlers', 318, 'cyclomatic', 'lizard', 1],
      ['addRoute', 322, 'cognitive', 'gocognit', 3],
      ['Routes', 349, 'cognitive', 'gocognit', 1],
      ['Routes', 349, 'cyclomatic', 'lizard', 2],
      ['Run', 376, 'cognitive', 'gocognit', 1],
      ['Run', 376, 'cyclomatic', 'lizard', 2],
      ['(anonymous)', 377, 'cyclomatic', 'lizard', 1],
      ['prepareTrustedCIDRs', 390, 'cognitive', 'gocognit', 12],
      ['prepareTrustedCIDRs', 390, 'cyclomatic', 'lizard', 8],
      ['SetTrustedProxies', 427, 'cognitive', 'gocognit', 0],
      ['SetTrustedProxies', 427, 'cyclomatic', 'lizard', 1],
      ['isUnsafeTrustedProxies', 433, 'cognitive', 'gocognit', 1],
      ['isUnsafeTrustedProxies', 433, 'cyclomatic', 'lizard', 2],
      ['parseTrustedProxies', 438, 'cognitive', 'gocognit', 0],
      ['parseTrustedProxies', 438, 'cyclomatic', 'lizard', 1],
      ['isTrustedProxy', 445, 'cognitive', 'gocognit', 4],
      ['isTrustedProxy', 445, 'cyclomatic', 'lizard', 4],
      ['validateHeader', 458, 'cognitive', 'gocognit', 7],
      ['validateHeader', 458, 'cyclomatic', 'lizard', 6],
      ['parseIP', 481, 'cognitive', 'gocognit', 1],
      ['parseIP', 481, 'cyclomatic', 'lizard', 2],
      ['RunTLS', 496, 'cognitive', 'gocognit', 1],
      ['(anonymous)', 498, 'cyclomatic', 'lizard', 1],
      ['RunUnix', 512, 'cognitive', 'gocognit', 2],
      ['RunUnix', 512, 'cyclomatic', 'lizard', 3],
      ['(anonymous)', 514, 'cyclomatic', 'lizard', 1],
      ['RunFd', 535, 'cognitive', 'gocognit', 2],
      ['RunFd', 535, 'cyclomatic', 'lizard', 3],
      ['(anonymous)', 537, 'cyclomatic', 'lizard', 1],
      ['RunListener', 556, 'cognitive', 'gocognit', 1],
      ['RunListener', 556, 'cyclomatic', 'lizard', 2],
      ['(anonymous)', 558, 'cyclomatic', 'lizard', 1],
      ['ServeHTTP', 570, 'cognitive', 'gocognit', 0],
      ['HandleContext', 584, 'cognitive', 'gocognit', 0],
      ['HandleContext', 584, 'cyclomatic', 'lizard', 1],
      ['handleHTTPRequest', 592, 'cognitive', 'gocognit', 30],
      ['handleHTTPRequest', 592, 'cyclomatic', 'lizard', 18],
      ['serveError', 654, 'cognitive', 'gocognit', 4],
      ['redirectTrailingSlash', 671, 'cognitive', 'gocognit', 3],
      ['redirectTrailingSlash', 671, 'cyclomatic', 'lizard', 4],
      ['redirectFixedPath', 687, 'cognitive', 'gocognit', 1],
      ['redirectRequest', 699, 'cognitive', 'gocognit', 1],
      ['redirectRequest', 699, 'cyclomatic', 'lizard', 2],
    ],
    knownDivergences: [['iterate', 356, 'cognitive', 'gocognit', 3, 2]],
  },
  {
    file: 'guava-33.0.0-Joiner.java',
    language: 'java',
    aggregates: {
      lines: {
        total: 519,
        code: 256,
        comment: 218,
        blank: 45,
      },
      functionCount: 41,
      classCount: 5,
      cyclomaticComplexity: 21,
      maxCyclomaticComplexity: 5,
      cognitiveComplexity: 23,
      maxCognitiveComplexity: 10,
      nestingDepth: 2,
      ncssCount: 150,
      callGraph: {
        callCount: 103,
        uniqueCalleeCount: 23,
        internalCallCount: 5,
        internalEdgeCount: 5,
        recursiveFunctionCount: 0,
        maxFanIn: 3,
        maxFanOut: 1,
        maxCallDepth: 1,
      },
      coupling: {
        importCount: 13,
        importSourceCount: 13,
        relativeImportCount: 0,
        externalImportCount: 13,
        exportCount: 0,
      },
      syntaxFeatures: {
        assignmentCount: 4,
        awaitExpressionCount: 0,
        loopStatementCount: 4,
        mutableBindingCount: 7,
        returnStatementCount: 36,
        throwStatementCount: 6,
        tryStatementCount: 2,
      },
      typeComplexity: {
        typeAnnotationCount: 0,
        typeAliasCount: 0,
        interfaceCount: 0,
        genericParameterCount: 8,
        unionTypeCount: 0,
        intersectionTypeCount: 0,
        conditionalTypeCount: 0,
        typeAssertionCount: 0,
        nonNullAssertionCount: 0,
        satisfiesExpressionCount: 0,
      },
      duplication: {
        duplicateBlockCount: 1,
        duplicateBlockGroupCount: 1,
        duplicateLineCount: 8,
        duplicationRatio: 0.0313,
        maxDuplicateBlockSize: 53,
      },
      halstead: {
        distinctOperators: 15,
        distinctOperands: 95,
        totalOperators: 265,
        totalOperands: 650,
        volume: 6204.9441,
      },
      maintainabilityIndex: 18.0854,
    },
    oracleFunctions: [
      ['on', 71, 'cognitive', 'pmd', 0],
      ['on', 71, 'cyclomatic', 'pmd', 1],
      ['on', 71, 'ncss', 'pmd', 2],
      ['on', 76, 'cognitive', 'pmd', 0],
      ['on', 76, 'cyclomatic', 'pmd', 1],
      ['on', 76, 'ncss', 'pmd', 2],
      ['Joiner', 82, 'cognitive', 'pmd', 0],
      ['Joiner', 82, 'cyclomatic', 'pmd', 1],
      ['Joiner', 82, 'ncss', 'pmd', 2],
      ['Joiner', 86, 'cognitive', 'pmd', 0],
      ['Joiner', 86, 'cyclomatic', 'pmd', 1],
      ['Joiner', 86, 'ncss', 'pmd', 2],
      ['appendTo', 100, 'cognitive', 'pmd', 0],
      ['appendTo', 100, 'cyclomatic', 'pmd', 1],
      ['appendTo', 100, 'ncss', 'pmd', 2],
      ['appendTo', 112, 'cognitive', 'pmd', 3],
      ['appendTo', 112, 'cyclomatic', 'pmd', 3],
      ['appendTo', 112, 'ncss', 'pmd', 8],
      ['appendTo', 130, 'cognitive', 'pmd', 0],
      ['appendTo', 130, 'cyclomatic', 'pmd', 1],
      ['appendTo', 130, 'ncss', 'pmd', 3],
      ['appendTo', 139, 'cognitive', 'pmd', 0],
      ['appendTo', 139, 'cyclomatic', 'pmd', 1],
      ['appendTo', 139, 'ncss', 'pmd', 2],
      ['appendTo', 154, 'cognitive', 'pmd', 0],
      ['appendTo', 154, 'cyclomatic', 'pmd', 1],
      ['appendTo', 154, 'ncss', 'pmd', 2],
      ['appendTo', 167, 'cognitive', 'pmd', 1],
      ['appendTo', 167, 'cyclomatic', 'pmd', 3],
      ['appendTo', 167, 'ncss', 'pmd', 5],
      ['appendTo', 183, 'cognitive', 'pmd', 0],
      ['appendTo', 183, 'cyclomatic', 'pmd', 1],
      ['appendTo', 183, 'ncss', 'pmd', 3],
      ['appendTo', 195, 'cognitive', 'pmd', 0],
      ['appendTo', 195, 'cyclomatic', 'pmd', 1],
      ['appendTo', 195, 'ncss', 'pmd', 2],
      ['join', 208, 'cognitive', 'pmd', 0],
      ['join', 208, 'cyclomatic', 'pmd', 1],
      ['join', 208, 'ncss', 'pmd', 2],
      ['join', 218, 'cognitive', 'pmd', 0],
      ['join', 218, 'cyclomatic', 'pmd', 1],
      ['join', 218, 'ncss', 'pmd', 2],
      ['join', 226, 'cognitive', 'pmd', 0],
      ['join', 226, 'cyclomatic', 'pmd', 1],
      ['join', 226, 'ncss', 'pmd', 3],
      ['join', 236, 'cognitive', 'pmd', 0],
      ['join', 236, 'cyclomatic', 'pmd', 1],
      ['join', 236, 'ncss', 'pmd', 2],
      ['useForNull', 245, 'cognitive', 'pmd', 2],
      ['useForNull', 245, 'cyclomatic', 'pmd', 1],
      ['toString', 248, 'cognitive', 'pmd', 1],
      ['toString', 248, 'cyclomatic', 'pmd', 2],
      ['toString', 248, 'ncss', 'pmd', 2],
      ['useForNull', 253, 'cognitive', 'pmd', 0],
      ['useForNull', 253, 'cyclomatic', 'pmd', 2],
      ['useForNull', 253, 'ncss', 'pmd', 2],
      ['skipNulls', 258, 'cognitive', 'pmd', 0],
      ['skipNulls', 258, 'cyclomatic', 'pmd', 2],
      ['skipNulls', 258, 'ncss', 'pmd', 2],
      ['skipNulls', 269, 'cognitive', 'pmd', 10],
      ['skipNulls', 269, 'cyclomatic', 'pmd', 1],
      ['appendTo', 271, 'cognitive', 'pmd', 6],
      ['appendTo', 271, 'cyclomatic', 'pmd', 5],
      ['appendTo', 271, 'ncss', 'pmd', 14],
      ['useForNull', 293, 'cognitive', 'pmd', 0],
      ['useForNull', 293, 'cyclomatic', 'pmd', 2],
      ['useForNull', 293, 'ncss', 'pmd', 2],
      ['withKeyValueSeparator', 298, 'cognitive', 'pmd', 0],
      ['withKeyValueSeparator', 298, 'cyclomatic', 'pmd', 2],
      ['withKeyValueSeparator', 298, 'ncss', 'pmd', 2],
      ['withKeyValueSeparator', 311, 'cognitive', 'pmd', 0],
      ['withKeyValueSeparator', 311, 'cyclomatic', 'pmd', 1],
      ['withKeyValueSeparator', 311, 'ncss', 'pmd', 2],
      ['withKeyValueSeparator', 319, 'cognitive', 'pmd', 0],
      ['withKeyValueSeparator', 319, 'cyclomatic', 'pmd', 1],
      ['withKeyValueSeparator', 319, 'ncss', 'pmd', 2],
      ['MapJoiner', 345, 'cognitive', 'pmd', 0],
      ['MapJoiner', 345, 'cyclomatic', 'pmd', 1],
      ['MapJoiner', 345, 'ncss', 'pmd', 3],
      ['appendTo', 354, 'cognitive', 'pmd', 0],
      ['appendTo', 354, 'cyclomatic', 'pmd', 1],
      ['appendTo', 354, 'ncss', 'pmd', 2],
      ['appendTo', 364, 'cognitive', 'pmd', 0],
      ['appendTo', 364, 'cyclomatic', 'pmd', 1],
      ['appendTo', 364, 'ncss', 'pmd', 2],
      ['appendTo', 375, 'cognitive', 'pmd', 0],
      ['appendTo', 375, 'cyclomatic', 'pmd', 1],
      ['appendTo', 375, 'ncss', 'pmd', 2],
      ['appendTo', 387, 'cognitive', 'pmd', 3],
      ['appendTo', 387, 'cyclomatic', 'pmd', 3],
      ['appendTo', 387, 'ncss', 'pmd', 14],
      ['appendTo', 414, 'cognitive', 'pmd', 0],
      ['appendTo', 414, 'cyclomatic', 'pmd', 1],
      ['appendTo', 414, 'ncss', 'pmd', 2],
      ['appendTo', 426, 'cognitive', 'pmd', 1],
      ['appendTo', 426, 'cyclomatic', 'pmd', 3],
      ['appendTo', 426, 'ncss', 'pmd', 5],
      ['join', 440, 'cognitive', 'pmd', 0],
      ['join', 440, 'cyclomatic', 'pmd', 1],
      ['join', 440, 'ncss', 'pmd', 2],
      ['join', 450, 'cognitive', 'pmd', 0],
      ['join', 450, 'cyclomatic', 'pmd', 1],
      ['join', 450, 'ncss', 'pmd', 2],
      ['join', 460, 'cognitive', 'pmd', 0],
      ['join', 460, 'cyclomatic', 'pmd', 1],
      ['join', 460, 'ncss', 'pmd', 2],
      ['useForNull', 468, 'cognitive', 'pmd', 0],
      ['useForNull', 468, 'cyclomatic', 'pmd', 1],
      ['useForNull', 468, 'ncss', 'pmd', 2],
      ['toString', 473, 'cognitive', 'pmd', 1],
      ['toString', 473, 'cyclomatic', 'pmd', 2],
      ['toString', 473, 'ncss', 'pmd', 3],
      ['iterable', 495, 'cognitive', 'pmd', 2],
      ['iterable', 495, 'cyclomatic', 'pmd', 1],
      ['size', 499, 'cognitive', 'pmd', 0],
      ['size', 499, 'cyclomatic', 'pmd', 1],
      ['size', 499, 'ncss', 'pmd', 2],
      ['get', 504, 'cognitive', 'pmd', 1],
      ['get', 504, 'cyclomatic', 'pmd', 3],
      ['get', 504, 'ncss', 'pmd', 8],
    ],
    knownDivergences: [
      ['useForNull', 245, 'ncss', 'pmd', 3, 9],
      ['skipNulls', 269, 'ncss', 'pmd', 2, 20],
      ['iterable', 495, 'ncss', 'pmd', 3, 13],
    ],
  },
  {
    file: 'mattermost-5.39.0-login_controller.jsx',
    language: 'jsx',
    aggregates: {
      lines: {
        total: 886,
        code: 784,
        comment: 20,
        blank: 82,
      },
      functionCount: 24,
      classCount: 1,
      cyclomaticComplexity: 94,
      maxCyclomaticComplexity: 25,
      cognitiveComplexity: 111,
      maxCognitiveComplexity: 22,
      nestingDepth: 2,
      ncssCount: 283,
      callGraph: {
        callCount: 119,
        uniqueCalleeCount: 41,
        internalCallCount: 0,
        internalEdgeCount: 0,
        recursiveFunctionCount: 0,
        maxFanIn: 0,
        maxFanOut: 0,
        maxCallDepth: 0,
      },
      coupling: {
        importCount: 26,
        importSourceCount: 26,
        relativeImportCount: 1,
        externalImportCount: 25,
        exportCount: 1,
      },
      syntaxFeatures: {
        assignmentCount: 24,
        awaitExpressionCount: 1,
        loopStatementCount: 0,
        mutableBindingCount: 10,
        returnStatementCount: 21,
        throwStatementCount: 0,
        tryStatementCount: 0,
      },
      typeComplexity: {
        typeAnnotationCount: 0,
        typeAliasCount: 0,
        interfaceCount: 0,
        genericParameterCount: 0,
        unionTypeCount: 0,
        intersectionTypeCount: 0,
        conditionalTypeCount: 0,
        typeAssertionCount: 0,
        nonNullAssertionCount: 0,
        satisfiesExpressionCount: 0,
      },
      duplication: {
        duplicateBlockCount: 2,
        duplicateBlockGroupCount: 1,
        duplicateLineCount: 60,
        duplicationRatio: 0.0765,
        maxDuplicateBlockSize: 74,
      },
      halstead: {
        distinctOperators: 27,
        distinctOperands: 395,
        totalOperators: 925,
        totalOperands: 1444,
        volume: 20_660.284,
      },
      maintainabilityIndex: 0,
    },
    oracleFunctions: [
      ['constructor', 70, 'cognitive', 'sonarjs', 4],
      ['componentDidMount', 95, 'cognitive', 'sonarjs', 7],
      ['componentWillUnmount', 137, 'cognitive', 'sonarjs', 1],
      ['(anonymous)', 144, 'cognitive', 'sonarjs', 2],
      ['(anonymous)', 144, 'cyclomatic', 'lizard', 2],
      ['(anonymous)', 167, 'cognitive', 'sonarjs', 1],
      ['(anonymous)', 167, 'cyclomatic', 'lizard', 2],
      ['(anonymous)', 174, 'cyclomatic', 'lizard', 1],
      ['(anonymous)', 176, 'cyclomatic', 'lizard', 1],
      ['(anonymous)', 185, 'cognitive', 'sonarjs', 16],
      ['(anonymous)', 270, 'cyclomatic', 'lizard', 14],
      ['(anonymous)', 325, 'cognitive', 'sonarjs', 5],
      ['(anonymous)', 346, 'cyclomatic', 'lizard', 1],
      ['(anonymous)', 352, 'cyclomatic', 'lizard', 1],
      ['(anonymous)', 358, 'cyclomatic', 'lizard', 1],
      ['(anonymous)', 362, 'cyclomatic', 'lizard', 4],
      ['(anonymous)', 392, 'cognitive', 'sonarjs', 8],
      ['(anonymous)', 392, 'cyclomatic', 'lizard', 7],
      ['(anonymous)', 425, 'cognitive', 'sonarjs', 1],
      ['(anonymous)', 425, 'cyclomatic', 'lizard', 7],
      ['(anonymous)', 435, 'cyclomatic', 'lizard', 1],
      ['(anonymous)', 440, 'cognitive', 'sonarjs', 7],
      ['(anonymous)', 537, 'cognitive', 'sonarjs', 22],
      ['render', 822, 'cognitive', 'sonarjs', 5],
    ],
    knownDivergences: [
      ['constructor', 70, 'cyclomatic', 'lizard', 3, 5],
      ['(anonymous)', 157, 'cognitive', 'sonarjs', 4, 7],
      ['(anonymous)', 157, 'cyclomatic', 'lizard', 6, 5],
      ['(anonymous)', 185, 'cyclomatic', 'lizard', 10, 12],
      ['(anonymous)', 270, 'cognitive', 'sonarjs', 16, 18],
      ['(anonymous)', 325, 'cyclomatic', 'lizard', 3, 5],
      ['(anonymous)', 362, 'cognitive', 'sonarjs', 3, 4],
      ['(anonymous)', 440, 'cyclomatic', 'lizard', 1, 8],
    ],
  },
  {
    file: 'nextjs-14.0.4-image-component.tsx',
    language: 'tsx',
    aggregates: {
      lines: {
        total: 417,
        code: 352,
        comment: 41,
        blank: 24,
      },
      functionCount: 20,
      classCount: 0,
      cyclomaticComplexity: 45,
      maxCyclomaticComplexity: 20,
      cognitiveComplexity: 82,
      maxCognitiveComplexity: 48,
      nestingDepth: 4,
      ncssCount: 119,
      callGraph: {
        callCount: 57,
        uniqueCalleeCount: 37,
        internalCallCount: 4,
        internalEdgeCount: 4,
        recursiveFunctionCount: 0,
        maxFanIn: 2,
        maxFanOut: 1,
        maxCallDepth: 1,
      },
      coupling: {
        importCount: 11,
        importSourceCount: 9,
        relativeImportCount: 6,
        externalImportCount: 3,
        exportCount: 5,
      },
      syntaxFeatures: {
        assignmentCount: 8,
        awaitExpressionCount: 0,
        loopStatementCount: 0,
        mutableBindingCount: 3,
        returnStatementCount: 10,
        throwStatementCount: 0,
        tryStatementCount: 0,
      },
      typeComplexity: {
        typeAnnotationCount: 23,
        typeAliasCount: 3,
        interfaceCount: 0,
        genericParameterCount: 0,
        unionTypeCount: 9,
        intersectionTypeCount: 2,
        conditionalTypeCount: 0,
        typeAssertionCount: 4,
        nonNullAssertionCount: 0,
        satisfiesExpressionCount: 0,
      },
      duplication: {
        duplicateBlockCount: 0,
        duplicateBlockGroupCount: 0,
        duplicateLineCount: 0,
        duplicationRatio: 0,
        maxDuplicateBlockSize: 0,
      },
      halstead: {
        distinctOperators: 25,
        distinctOperands: 197,
        totalOperators: 286,
        totalOperands: 551,
        volume: 6523.9261,
      },
      maintainabilityIndex: 11.6879,
    },
    oracleFunctions: [
      ['(anonymous)', 74, 'cognitive', 'sonarjs', 33],
      ['(anonymous)', 99, 'cyclomatic', 'lizard', 1],
      ['(anonymous)', 100, 'cyclomatic', 'lizard', 1],
      ['(anonymous)', 101, 'cyclomatic', 'lizard', 1],
      ['(anonymous)', 102, 'cyclomatic', 'lizard', 1],
      ['(anonymous)', 106, 'cyclomatic', 'lizard', 1],
      ['getDynamicProps', 163, 'cognitive', 'sonarjs', 3],
      ['(anonymous)', 230, 'cognitive', 'sonarjs', 12],
      ['(anonymous)', 280, 'cyclomatic', 'lizard', 1],
      ['(anonymous)', 291, 'cognitive', 'sonarjs', 2],
      ['(anonymous)', 291, 'cyclomatic', 'lizard', 3],
      ['ImagePreload', 307, 'cognitive', 'sonarjs', 3],
      ['(anonymous)', 362, 'cognitive', 'sonarjs', 1],
      ['(anonymous)', 362, 'cyclomatic', 'lizard', 3],
      ['(anonymous)', 364, 'cyclomatic', 'lizard', 1],
      ['(anonymous)', 365, 'cyclomatic', 'lizard', 1],
      ['(anonymous)', 372, 'cyclomatic', 'lizard', 1],
      ['(anonymous)', 378, 'cyclomatic', 'lizard', 1],
    ],
    knownDivergences: [
      ['handleLoading', 60, 'cognitive', 'sonarjs', 3, 48],
      ['(anonymous)', 74, 'cyclomatic', 'lizard', 1, 20],
      ['(anonymous)', 74, 'cyclomatic', 'lizard', 22, 20],
      ['getDynamicProps', 163, 'cyclomatic', 'lizard', 5, 4],
      ['Image', 356, 'cognitive', 'sonarjs', 1, 2],
    ],
  },
  {
    file: 'rails-7.1.2-methods.rb',
    language: 'ruby',
    aggregates: {
      lines: {
        total: 388,
        code: 127,
        comment: 229,
        blank: 32,
      },
      functionCount: 30,
      classCount: 2,
      cyclomaticComplexity: 35,
      maxCyclomaticComplexity: 8,
      cognitiveComplexity: 43,
      maxCognitiveComplexity: 10,
      nestingDepth: 2,
      ncssCount: 99,
      callGraph: {
        callCount: 102,
        uniqueCalleeCount: 53,
        internalCallCount: 12,
        internalEdgeCount: 12,
        recursiveFunctionCount: 0,
        maxFanIn: 3,
        maxFanOut: 2,
        maxCallDepth: 2,
      },
      coupling: {
        importCount: 1,
        importSourceCount: 1,
        relativeImportCount: 0,
        externalImportCount: 1,
        exportCount: 0,
      },
      syntaxFeatures: {
        assignmentCount: 13,
        awaitExpressionCount: 0,
        loopStatementCount: 0,
        mutableBindingCount: 0,
        returnStatementCount: 3,
        throwStatementCount: 0,
        tryStatementCount: 1,
      },
      typeComplexity: {
        typeAnnotationCount: 0,
        typeAliasCount: 0,
        interfaceCount: 0,
        genericParameterCount: 0,
        unionTypeCount: 0,
        intersectionTypeCount: 0,
        conditionalTypeCount: 0,
        typeAssertionCount: 0,
        nonNullAssertionCount: 0,
        satisfiesExpressionCount: 0,
      },
      duplication: {
        duplicateBlockCount: 0,
        duplicateBlockGroupCount: 0,
        duplicateLineCount: 0,
        duplicationRatio: 0,
        maxDuplicateBlockSize: 0,
      },
      halstead: {
        distinctOperators: 16,
        distinctOperands: 135,
        totalOperators: 163,
        totalOperands: 363,
        volume: 3807.4009,
      },
      maintainabilityIndex: 24.3285,
    },
    oracleFunctions: [
      ['upcase_first', 166, 'cyclomatic', 'lizard', 2],
      ['downcase_first', 175, 'cyclomatic', 'lizard', 2],
      ['ordinal', 334, 'cyclomatic', 'lizard', 1],
      ['ordinalize', 347, 'cyclomatic', 'lizard', 1],
    ],
    knownDivergences: [
      ['underscore', 99, 'cyclomatic', 'lizard', 6, 2],
      ['const_regexp', 357, 'cyclomatic', 'lizard', 3, 2],
    ],
  },
  {
    file: 'redis-7.2.3-intset.c',
    language: 'c',
    aggregates: {
      lines: {
        total: 561,
        code: 416,
        comment: 76,
        blank: 69,
      },
      functionCount: 26,
      classCount: 0,
      cyclomaticComplexity: 57,
      maxCyclomaticComplexity: 13,
      cognitiveComplexity: 87,
      maxCognitiveComplexity: 24,
      nestingDepth: 3,
      ncssCount: 380,
      callGraph: {
        callCount: 252,
        uniqueCalleeCount: 35,
        internalCallCount: 38,
        internalEdgeCount: 38,
        recursiveFunctionCount: 0,
        maxFanIn: 7,
        maxFanOut: 12,
        maxCallDepth: 5,
      },
      coupling: {
        importCount: 9,
        importSourceCount: 9,
        relativeImportCount: 4,
        externalImportCount: 5,
        exportCount: 0,
      },
      syntaxFeatures: {
        assignmentCount: 87,
        awaitExpressionCount: 0,
        loopStatementCount: 9,
        mutableBindingCount: 56,
        returnStatementCount: 37,
        throwStatementCount: 0,
        tryStatementCount: 0,
      },
      typeComplexity: {
        typeAnnotationCount: 0,
        typeAliasCount: 0,
        interfaceCount: 0,
        genericParameterCount: 0,
        unionTypeCount: 0,
        intersectionTypeCount: 0,
        conditionalTypeCount: 0,
        typeAssertionCount: 0,
        nonNullAssertionCount: 0,
        satisfiesExpressionCount: 0,
      },
      duplication: {
        duplicateBlockCount: 2,
        duplicateBlockGroupCount: 2,
        duplicateLineCount: 60,
        duplicationRatio: 0.1442,
        maxDuplicateBlockSize: 180,
      },
      halstead: {
        distinctOperators: 26,
        distinctOperands: 164,
        totalOperators: 464,
        totalOperands: 1211,
        volume: 12_679.5081,
      },
      maintainabilityIndex: 6.4705,
    },
    oracleFunctions: [
      ['_intsetValueEncoding', 46, 'cyclomatic', 'lizard', 5],
      ['intsetNew', 98, 'cyclomatic', 'lizard', 1],
      ['intsetRandom', 262, 'cyclomatic', 'lizard', 1],
      ['intsetMax', 269, 'cyclomatic', 'lizard', 1],
      ['intsetMin', 275, 'cyclomatic', 'lizard', 1],
      ['intsetLen', 290, 'cyclomatic', 'lizard', 1],
      ['intsetBlobLen', 295, 'cyclomatic', 'lizard', 1],
      ['intsetRepr', 350, 'cyclomatic', 'lizard', 2],
      ['error', 357, 'cyclomatic', 'lizard', 1],
      ['ok', 363, 'cyclomatic', 'lizard', 1],
      ['usec', 367, 'cyclomatic', 'lizard', 1],
      ['checkConsistency', 389, 'cyclomatic', 'lizard', 4],
    ],
    knownDivergences: [],
  },
  {
    file: 'requests-2.31.0-sessions.py',
    language: 'python',
    aggregates: {
      lines: {
        total: 834,
        code: 564,
        comment: 116,
        blank: 154,
      },
      functionCount: 28,
      classCount: 2,
      cyclomaticComplexity: 81,
      maxCyclomaticComplexity: 15,
      cognitiveComplexity: 94,
      maxCognitiveComplexity: 26,
      nestingDepth: 3,
      ncssCount: 294,
      callGraph: {
        callCount: 137,
        uniqueCalleeCount: 90,
        internalCallCount: 4,
        internalEdgeCount: 4,
        recursiveFunctionCount: 0,
        maxFanIn: 3,
        maxFanOut: 2,
        maxCallDepth: 2,
      },
      coupling: {
        importCount: 16,
        importSourceCount: 16,
        relativeImportCount: 11,
        externalImportCount: 5,
        exportCount: 0,
      },
      syntaxFeatures: {
        assignmentCount: 99,
        awaitExpressionCount: 0,
        loopStatementCount: 9,
        mutableBindingCount: 0,
        returnStatementCount: 29,
        throwStatementCount: 3,
        tryStatementCount: 3,
      },
      typeComplexity: {
        typeAnnotationCount: 0,
        typeAliasCount: 0,
        interfaceCount: 0,
        genericParameterCount: 0,
        unionTypeCount: 0,
        intersectionTypeCount: 0,
        conditionalTypeCount: 0,
        typeAssertionCount: 0,
        nonNullAssertionCount: 0,
        satisfiesExpressionCount: 0,
      },
      duplication: {
        duplicateBlockCount: 0,
        duplicateBlockGroupCount: 0,
        duplicateLineCount: 0,
        duplicationRatio: 0,
        maxDuplicateBlockSize: 0,
      },
      halstead: {
        distinctOperators: 17,
        distinctOperands: 266,
        totalOperators: 521,
        totalOperands: 1135,
        volume: 13_487.5541,
      },
      maintainabilityIndex: 0.1711,
    },
    oracleFunctions: [
      ['merge_hooks', 91, 'cognitive', 'complexipy', 4],
      ['get_redirect_target', 107, 'cognitive', 'complexipy', 1],
      ['should_strip_auth', 127, 'cognitive', 'complexipy', 6],
      ['resolve_redirects', 159, 'cognitive', 'complexipy', 26],
      ['rebuild_auth', 283, 'cognitive', 'complexipy', 4],
      ['rebuild_proxies', 303, 'cognitive', 'complexipy', 4],
      ['rebuild_method', 334, 'cognitive', 'complexipy', 6],
      ['__init__', 391, 'cognitive', 'complexipy', 0],
      ['__init__', 391, 'cyclomatic', 'lizard', 1],
      ['__enter__', 453, 'cognitive', 'complexipy', 0],
      ['__enter__', 453, 'cyclomatic', 'lizard', 1],
      ['__exit__', 456, 'cognitive', 'complexipy', 0],
      ['prepare_request', 459, 'cognitive', 'complexipy', 4],
      ['get', 593, 'cognitive', 'complexipy', 0],
      ['options', 604, 'cognitive', 'complexipy', 0],
      ['head', 615, 'cognitive', 'complexipy', 0],
      ['post', 626, 'cognitive', 'complexipy', 0],
      ['put', 639, 'cognitive', 'complexipy', 0],
      ['patch', 651, 'cognitive', 'complexipy', 0],
      ['delete', 663, 'cognitive', 'complexipy', 0],
      ['merge_environment_settings', 751, 'cognitive', 'complexipy', 9],
      ['get_adapter', 782, 'cognitive', 'complexipy', 3],
      ['close', 796, 'cognitive', 'complexipy', 1],
      ['close', 796, 'cyclomatic', 'lizard', 2],
      ['__setstate__', 816, 'cognitive', 'complexipy', 1],
      ['session', 821, 'cognitive', 'complexipy', 0],
      ['session', 821, 'cyclomatic', 'lizard', 1],
    ],
    knownDivergences: [
      ['merge_setting', 61, 'cognitive', 'complexipy', 7, 6],
      ['request', 502, 'cognitive', 'complexipy', 1, 3],
      ['send', 673, 'cognitive', 'complexipy', 14, 12],
      ['mount', 801, 'cognitive', 'complexipy', 3, 2],
      ['__getstate__', 812, 'cognitive', 'complexipy', 1, 0],
      ['__getstate__', 812, 'cyclomatic', 'lizard', 2, 1],
    ],
  },
  {
    file: 'ripgrep-14.1.0-gitignore.rs',
    language: 'rust',
    aggregates: {
      lines: {
        total: 817,
        code: 562,
        comment: 193,
        blank: 62,
      },
      functionCount: 64,
      classCount: 3,
      cyclomaticComplexity: 60,
      maxCyclomaticComplexity: 14,
      cognitiveComplexity: 69,
      maxCognitiveComplexity: 18,
      nestingDepth: 3,
      ncssCount: 360,
      callGraph: {
        callCount: 265,
        uniqueCalleeCount: 94,
        internalCallCount: 61,
        internalEdgeCount: 61,
        recursiveFunctionCount: 7,
        maxFanIn: 7,
        maxFanOut: 5,
        maxCallDepth: 5,
      },
      coupling: {
        importCount: 7,
        importSourceCount: 15,
        relativeImportCount: 7,
        externalImportCount: 8,
        exportCount: 0,
      },
      syntaxFeatures: {
        assignmentCount: 18,
        awaitExpressionCount: 0,
        loopStatementCount: 4,
        mutableBindingCount: 15,
        returnStatementCount: 15,
        throwStatementCount: 0,
        tryStatementCount: 0,
      },
      typeComplexity: {
        typeAnnotationCount: 0,
        typeAliasCount: 0,
        interfaceCount: 0,
        genericParameterCount: 0,
        unionTypeCount: 0,
        intersectionTypeCount: 0,
        conditionalTypeCount: 0,
        typeAssertionCount: 0,
        nonNullAssertionCount: 0,
        satisfiesExpressionCount: 0,
      },
      duplication: {
        duplicateBlockCount: 0,
        duplicateBlockGroupCount: 0,
        duplicateLineCount: 0,
        duplicationRatio: 0,
        maxDuplicateBlockSize: 0,
      },
      halstead: {
        distinctOperators: 23,
        distinctOperands: 388,
        totalOperators: 799,
        totalOperands: 1548,
        volume: 20_378.9883,
      },
      maintainabilityIndex: 1.7742,
    },
    oracleFunctions: [
      ['from', 47, 'cyclomatic', 'lizard', 1],
      ['original', 52, 'cyclomatic', 'lizard', 1],
      ['actual', 58, 'cyclomatic', 'lizard', 1],
      ['is_whitelist', 63, 'cyclomatic', 'lizard', 1],
      ['is_only_dir', 68, 'cyclomatic', 'lizard', 1],
      ['has_doublestar_prefix', 73, 'cyclomatic', 'lizard', 2],
      ['global', 130, 'cyclomatic', 'lizard', 1],
      ['empty', 137, 'cyclomatic', 'lizard', 1],
      ['path', 151, 'cyclomatic', 'lizard', 1],
      ['is_empty', 157, 'cyclomatic', 'lizard', 1],
      ['len', 163, 'cyclomatic', 'lizard', 1],
      ['num_ignores', 168, 'cyclomatic', 'lizard', 1],
      ['num_whitelists', 173, 'cyclomatic', 'lizard', 1],
      ['new', 320, 'cyclomatic', 'lizard', 1],
      ['home_dir', 630, 'cyclomatic', 'lizard', 1],
      ['bytes', 747, 'cyclomatic', 'lizard', 1],
      ['path_string', 751, 'cyclomatic', 'lizard', 1],
      ['parse_excludes_file1', 756, 'cyclomatic', 'lizard', 1],
      ['parse_excludes_file2', 763, 'cyclomatic', 'lizard', 1],
      ['parse_excludes_file3', 770, 'cyclomatic', 'lizard', 1],
      ['parse_excludes_file4', 776, 'cyclomatic', 'lizard', 1],
      ['parse_excludes_file5', 786, 'cyclomatic', 'lizard', 1],
      ['regression_106', 793, 'cyclomatic', 'lizard', 1],
      ['case_insensitive', 798, 'cyclomatic', 'lizard', 1],
    ],
    knownDivergences: [
      ['build', 333, 'cyclomatic', 'lizard', 3, 1],
      ['build_global', 359, 'cyclomatic', 'lizard', 4, 6],
      ['gitconfig_excludes_path', 537, 'cyclomatic', 'lizard', 3, 5],
      ['gitconfig_home_contents', 555, 'cyclomatic', 'lizard', 3, 5],
      ['gitconfig_xdg_contents', 570, 'cyclomatic', 'lizard', 4, 3],
      ['excludes_file_default', 586, 'cyclomatic', 'lizard', 3, 1],
      ['parse_excludes_file', 595, 'cyclomatic', 'lizard', 3, 1],
      ['expand_tilde', 621, 'cyclomatic', 'lizard', 2, 3],
    ],
  },
  {
    file: 'vscode-1.85.0-uri.ts',
    language: 'typescript',
    aggregates: {
      lines: {
        total: 746,
        code: 469,
        comment: 199,
        blank: 78,
      },
      functionCount: 25,
      classCount: 4,
      cyclomaticComplexity: 157,
      maxCyclomaticComplexity: 28,
      cognitiveComplexity: 181,
      maxCognitiveComplexity: 32,
      nestingDepth: 4,
      ncssCount: 312,
      callGraph: {
        callCount: 92,
        uniqueCalleeCount: 28,
        internalCallCount: 14,
        internalEdgeCount: 14,
        recursiveFunctionCount: 1,
        maxFanIn: 3,
        maxFanOut: 3,
        maxCallDepth: 2,
      },
      coupling: {
        importCount: 4,
        importSourceCount: 4,
        relativeImportCount: 0,
        externalImportCount: 4,
        exportCount: 12,
      },
      syntaxFeatures: {
        assignmentCount: 83,
        awaitExpressionCount: 0,
        loopStatementCount: 2,
        mutableBindingCount: 12,
        returnStatementCount: 35,
        throwStatementCount: 5,
        tryStatementCount: 1,
      },
      typeComplexity: {
        typeAnnotationCount: 99,
        typeAliasCount: 1,
        interfaceCount: 2,
        genericParameterCount: 1,
        unionTypeCount: 26,
        intersectionTypeCount: 0,
        conditionalTypeCount: 1,
        typeAssertionCount: 21,
        nonNullAssertionCount: 0,
        satisfiesExpressionCount: 0,
      },
      duplication: {
        duplicateBlockCount: 0,
        duplicateBlockGroupCount: 0,
        duplicateLineCount: 0,
        duplicationRatio: 0,
        maxDuplicateBlockSize: 0,
      },
      halstead: {
        distinctOperators: 30,
        distinctOperands: 193,
        totalOperators: 706,
        totalOperands: 1233,
        volume: 15_125.9449,
      },
      maintainabilityIndex: 0,
    },
    oracleFunctions: [
      ['_validateUri', 15, 'cognitive', 'sonarjs', 14],
      ['_schemeFix', 50, 'cognitive', 'sonarjs', 2],
      ['_referenceResolution', 58, 'cognitive', 'sonarjs', 4],
      ['isUri', 100, 'cognitive', 'sonarjs', 3],
      ['constructor', 157, 'cognitive', 'sonarjs', 11],
      ['with', 214, 'cognitive', 'sonarjs', 13],
      ['parse', 267, 'cognitive', 'sonarjs', 6],
      ['file', 303, 'cognitive', 'sonarjs', 7],
      ['joinPath', 356, 'cognitive', 'sonarjs', 4],
      ['fsPath', 452, 'cognitive', 'sonarjs', 1],
      ['toString', 459, 'cognitive', 'sonarjs', 4],
      ['toJSON', 471, 'cognitive', 'sonarjs', 7],
      ['encodeURIComponentMinimal', 596, 'cognitive', 'sonarjs', 12],
      ['_asFormatted', 647, 'cognitive', 'sonarjs', 32],
      ['decodeURIComponentGraceful', 719, 'cognitive', 'sonarjs', 4],
      ['percentDecode', 733, 'cognitive', 'sonarjs', 1],
    ],
    knownDivergences: [
      ['revive', 404, 'cognitive', 'sonarjs', 7, 5],
      ['isUriComponents', 426, 'cognitive', 'sonarjs', 10, 7],
      ['encodeURIComponentFast', 532, 'cognitive', 'sonarjs', 36, 31],
      ['uriToFsPath', 617, 'cognitive', 'sonarjs', 11, 12],
    ],
  },
];
