import type { LanguageName } from '../../src/index.js';

/**
 * Expected metrics for the real-world OSS corpus under test/fixtures/oss (famous open-source
 * files pinned to release tags; see test/fixtures/oss/README.md for provenance and licenses).
 *
 * The per-function complexity/NCSS oracle values were produced by major existing tools, NOT by
 * code-gauge itself, so these tests verify code-gauge against independent implementations:
 *
 * - `pmd` — PMD 7.26.0 (CyclomaticComplexity / CognitiveComplexity / NcssCount rules, report
 *   level 1), the engine whose semantics code-gauge's Java complexity deliberately follows.
 *   All 41 Java methods match on cyclomatic AND cognitive complexity; NCSS matches on 38.
 * - `lizard` — lizard 1.23.0 cyclomatic complexity (CCN), attributed to functions by matching
 *   its start/end lines to code-gauge's (lizard's JS/TS line numbers are one lower than
 *   tree-sitter's; Java starts differ by annotation lines, joined via their unique end line).
 *   266 functions match across every language except Ruby-heavy constructs (see below).
 * - `gocognit` — gocognit v1.2.0, the standard Go implementation of SonarSource cognitive
 *   complexity. 37 of 38 functions match.
 * - `complexipy` — complexipy 7.0.0, a Rust implementation of SonarSource cognitive complexity
 *   for Python. 23 of 28 functions match.
 * - `sonarjs` — eslint-plugin-sonarjs 0.25.1 (SonarSource's own ESLint port of cognitive
 *   complexity) on ESLint 8.57.0 / @typescript-eslint/parser 7.18.0. 57 functions match across
 *   JavaScript, TypeScript, JSX, and TSX.
 *
 * A handful of tool rows could not be attributed to exactly one code-gauge function and are in
 * neither list: two lizard rows spanning misparsed JSX (mattermost's `createLoginOptions` and
 * `hideMfa`), the four one-line lizard rows for vscode's `revive` TypeScript overload signatures
 * (declarations rather than functions), and two sonarjs rows in the Next.js fixture whose
 * reported position matches no single function (@74:29 and @205:5).
 *
 * Line metrics in `aggregates` were verified against cloc 2.06 for all files (code/comment/blank
 * identical; code-gauge additionally counts the empty line after a trailing final newline as one
 * blank line, so `lines.total` and `lines.blank` are one higher than cloc's). Two files need a
 * different oracle:
 *
 * - Python: cloc classifies docstrings as comments while code-gauge (like tree-sitter) treats
 *   them as expression statements, i.e. code. For requests' sessions.py cloc reports
 *   code=413/comment=267; code-gauge reports code=564/comment=116 — the code+comment sum (680)
 *   is identical, and the 151-line delta is exactly the docstring lines.
 * - Rust: cloc misparses gitignore.rs because glob patterns such as "foo/**" + "/*" inside string
 *   literals look like block-comment openers to it. tokei 13.0 (Rust-aware) confirms code-gauge:
 *   code=562 for both; tokei's comment(165)+doc-comment-blank(29)=194 vs code-gauge's 193+blank
 *   split differs only in how blank lines inside doc comments are classified.
 *
 * `knownDivergences` pins every attributable function where an oracle tool disagrees with
 * code-gauge, so a behavior change on either side of a documented gap fails loudly. The reasons:
 *
 * - pmd/ncss: PMD's NCSS visitor does not descend into expression positions (anonymous classes
 *   returned from methods), while code-gauge counts statement-shaped content uniformly — the same
 *   deliberate divergence documented in pmdParity.test.ts.
 * - gocognit/cognitive: gocognit charges SonarSource's +1 recursion increment (gin's `iterate`);
 *   code-gauge does not charge recursion (issue #22 — intentionally omitted, like PMD and the
 *   SonarQube analyzers, and unsound under file-local receiver-blind call resolution).
 * - complexipy/cognitive: complexipy charges comprehensions and their internal `if`/`for` clauses;
 *   code-gauge counts only statement-level decisions (dialect difference among Sonar ports).
 * - sonarjs/cognitive: sonarjs attributes nested-closure content to the innermost enclosing
 *   function only, while code-gauge (like PMD) also attributes it to the enclosing declared
 *   function; a few remaining cases differ on JSX expressions, which sonarjs does not analyze,
 *   and on `??`/optional-chain handling in vscode's uri.ts.
 * - lizard/cyclomatic: lizard folds anonymous-class methods into the enclosing Java method
 *   (guava's `iterable`), does not see JSX expression trees (jsx), Ruby modifier conditionals
 *   and multi-class `rescue` clauses (ruby), Python comprehension clauses (python), or Rust
 *   attribute/macro-heavy constructs (rust) the way a real grammar does, and counts `case`
 *   fall-through labels differently in a few C-family switches.
 *
 * Aggregate float values (cohesion, duplicationRatio, halstead, maintainabilityIndex) are rounded
 * to 4 decimals by the same rounding the test applies to measured values before comparison.
 *
 * Regeneration: run the tools above at the pinned versions over test/fixtures/oss, join their
 * per-function rows to code-gauge functions by start/end line, and re-emit this file; expected
 * values only change when the measurer's semantics change, in which case the affected entries
 * must be re-verified against the tools.
 */

export type OracleMetric = 'cyclomatic' | 'cognitive' | 'ncss';

/**
 * [functionName, startLine, endLine, metric, tool, expectedValue] — code-gauge must equal
 * expectedValue for the function spanning exactly startLine..endLine.
 */
export type OracleFunctionEntry = readonly [string, number, number, OracleMetric, string, number];

/**
 * [functionName, startLine, endLine, metric, tool, toolValue, codeGaugeValue] — code-gauge must
 * equal codeGaugeValue, which intentionally differs from toolValue (see file doc above). If an
 * implementation change makes code-gauge match the tool, move the entry to oracleFunctions.
 */
export type KnownDivergenceEntry = readonly [string, number, number, OracleMetric, string, number, number];

export interface OssAggregateExpectation {
  lines: { total: number; code: number; comment: number; blank: number };
  functionCount: number;
  classCount: number;
  cyclomaticComplexity: number;
  maxCyclomaticComplexity: number;
  cognitiveComplexity: number;
  maxCognitiveComplexity: number;
  nestingDepth: number;
  ncssCount: number;
  callGraph: Record<string, number>;
  coupling: Record<string, number>;
  module: { declarations: { exported: boolean; name: string; startLine: number }[]; importSources: string[] };
  cohesion: Record<string, number>;
  syntaxFeatures: Record<string, number>;
  typeComplexity: Record<string, number>;
  duplication: {
    duplicateBlockCount: number;
    duplicateBlockGroupCount: number;
    duplicateBlockGroups: { endLine: number; startLine: number }[][];
    duplicateLineCount: number;
    duplicationRatio: number;
    maxDuplicateBlockSize: number;
  };
  halstead: Record<string, number>;
  maintainabilityIndex: number;
}

export interface OssFileExpectation {
  file: string;
  language: LanguageName;
  aggregates: OssAggregateExpectation;
  oracleFunctions: readonly OracleFunctionEntry[];
  knownDivergences: readonly KnownDivergenceEntry[];
}

export const ossExpectations: readonly OssFileExpectation[] = [
  {
    file: 'bitcoin-25.0-bech32.cpp',
    language: 'cpp',
    aggregates: {
      lines: {
        total: 570,
        code: 286,
        comment: 219,
        blank: 65,
      },
      functionCount: 13,
      classCount: 0,
      cyclomaticComplexity: 79,
      maxCyclomaticComplexity: 35,
      cognitiveComplexity: 149,
      maxCognitiveComplexity: 89,
      nestingDepth: 5,
      ncssCount: 240,
      callGraph: {
        callCount: 113,
        uniqueCalleeCount: 23,
        internalCallCount: 17,
        internalEdgeCount: 16,
        recursiveFunctionCount: 0,
        maxFanIn: 3,
        maxFanOut: 6,
        maxCallDepth: 2,
      },
      coupling: {
        importCount: 6,
        importSourceCount: 6,
        relativeImportCount: 0,
        externalImportCount: 6,
        exportCount: 0,
      },
      module: {
        declarations: [
          {
            exported: false,
            name: 'bech32::Encode',
            startLine: 357,
          },
          {
            exported: false,
            name: 'bech32::Decode',
            startLine: 373,
          },
          {
            exported: false,
            name: 'bech32::LocateErrors',
            startLine: 400,
          },
        ],
        importSources: ['bech32.h', 'util/vector.h', 'array', 'assert.h', 'numeric', 'optional'],
      },
      cohesion: {
        averageFunctionIdentifierOverlap: 0.0829,
        sharedIdentifierCount: 43,
        uniqueIdentifierCount: 96,
      },
      syntaxFeatures: {
        assignmentCount: 48,
        awaitExpressionCount: 0,
        loopStatementCount: 17,
        mutableBindingCount: 82,
        returnStatementCount: 25,
        throwStatementCount: 0,
        tryStatementCount: 0,
      },
      typeComplexity: {
        typeAnnotationCount: 0,
        typeAliasCount: 0,
        interfaceCount: 0,
        genericParameterCount: 0,
        unionTypeCount: 0,
        intersectionTypeCount: 0,
        conditionalTypeCount: 0,
        typeAssertionCount: 0,
        nonNullAssertionCount: 0,
        satisfiesExpressionCount: 0,
      },
      duplication: {
        duplicateBlockCount: 2,
        duplicateBlockGroupCount: 1,
        duplicateBlockGroups: [
          [
            {
              endLine: 500,
              startLine: 498,
            },
            {
              endLine: 506,
              startLine: 504,
            },
            {
              endLine: 521,
              startLine: 519,
            },
          ],
        ],
        duplicateLineCount: 9,
        duplicationRatio: 0.0315,
        maxDuplicateBlockSize: 44,
      },
      halstead: {
        distinctOperators: 28,
        distinctOperands: 185,
        totalOperators: 571,
        totalOperands: 1089,
        vocabulary: 213,
        length: 1660,
        volume: 12_839.618,
        difficulty: 82.4108,
        effort: 1_058_123.3274,
        time: 58_784.6293,
        bugs: 4.2799,
      },
      maintainabilityIndex: 7.0231,
    },
    oracleFunctions: [
      ['GenerateGFTables', 46, 115, 'cyclomatic', 'lizard', 6],
      ['EncodingConstant', 122, 125, 'cyclomatic', 'lizard', 3],
      ['PolyMod', 130, 216, 'cyclomatic', 'lizard', 7],
      ['GenerateSyndromeConstants', 240, 254, 'cyclomatic', 'lizard', 3],
      ['Syndrome', 261, 278, 'cyclomatic', 'lizard', 3],
      ['LowerCase', 281, 284, 'cyclomatic', 'lizard', 3],
      ['CheckCharacters', 287, 309, 'cyclomatic', 'lizard', 10],
      ['ExpandHRP', 312, 324, 'cyclomatic', 'lizard', 2],
      ['VerifyChecksum', 327, 338, 'cyclomatic', 'lizard', 3],
      ['CreateChecksum', 341, 352, 'cyclomatic', 'lizard', 2],
      ['Encode', 357, 370, 'cyclomatic', 'lizard', 4],
      ['Decode', 373, 397, 'cyclomatic', 'lizard', 10],
      ['LocateErrors', 400, 567, 'cyclomatic', 'lizard', 35],
    ],
    knownDivergences: [],
  },
  {
    file: 'express-4.18.2-response.js',
    language: 'javascript',
    aggregates: {
      lines: {
        total: 1170,
        code: 537,
        comment: 475,
        blank: 158,
      },
      functionCount: 42,
      classCount: 0,
      cyclomaticComplexity: 134,
      maxCyclomaticComplexity: 30,
      cognitiveComplexity: 187,
      maxCognitiveComplexity: 39,
      nestingDepth: 4,
      ncssCount: 428,
      callGraph: {
        callCount: 184,
        uniqueCalleeCount: 70,
        internalCallCount: 22,
        internalEdgeCount: 21,
        recursiveFunctionCount: 4,
        maxFanIn: 6,
        maxFanOut: 2,
        maxCallDepth: 5,
      },
      coupling: {
        importCount: 0,
        importSourceCount: 0,
        relativeImportCount: 0,
        externalImportCount: 0,
        exportCount: 0,
      },
      module: {
        declarations: [
          {
            exported: false,
            name: 'Buffer',
            startLine: 15,
          },
          {
            exported: false,
            name: 'contentDisposition',
            startLine: 16,
          },
          {
            exported: false,
            name: 'createError',
            startLine: 17,
          },
          {
            exported: false,
            name: 'deprecate',
            startLine: 18,
          },
          {
            exported: false,
            name: 'encodeUrl',
            startLine: 19,
          },
          {
            exported: false,
            name: 'escapeHtml',
            startLine: 20,
          },
          {
            exported: false,
            name: 'http',
            startLine: 21,
          },
          {
            exported: false,
            name: 'isAbsolute',
            startLine: 22,
          },
          {
            exported: false,
            name: 'onFinished',
            startLine: 23,
          },
          {
            exported: false,
            name: 'path',
            startLine: 24,
          },
          {
            exported: false,
            name: 'statuses',
            startLine: 25,
          },
          {
            exported: false,
            name: 'merge',
            startLine: 26,
          },
          {
            exported: false,
            name: 'sign',
            startLine: 27,
          },
          {
            exported: false,
            name: 'normalizeType',
            startLine: 28,
          },
          {
            exported: false,
            name: 'normalizeTypes',
            startLine: 29,
          },
          {
            exported: false,
            name: 'setCharset',
            startLine: 30,
          },
          {
            exported: false,
            name: 'cookie',
            startLine: 31,
          },
          {
            exported: false,
            name: 'send',
            startLine: 32,
          },
          {
            exported: false,
            name: 'extname',
            startLine: 33,
          },
          {
            exported: false,
            name: 'mime',
            startLine: 34,
          },
          {
            exported: false,
            name: 'resolve',
            startLine: 35,
          },
          {
            exported: false,
            name: 'vary',
            startLine: 36,
          },
          {
            exported: false,
            name: 'res',
            startLine: 43,
          },
          {
            exported: false,
            name: 'charsetRegExp',
            startLine: 57,
          },
          {
            exported: false,
            name: 'sendfile',
            startLine: 1043,
          },
          {
            exported: false,
            name: 'stringify',
            startLine: 1145,
          },
        ],
        importSources: [],
      },
      cohesion: {
        averageFunctionIdentifierOverlap: 0.0484,
        sharedIdentifierCount: 93,
        uniqueIdentifierCount: 157,
      },
      syntaxFeatures: {
        assignmentCount: 101,
        awaitExpressionCount: 0,
        loopStatementCount: 3,
        mutableBindingCount: 103,
        returnStatementCount: 41,
        throwStatementCount: 5,
        tryStatementCount: 0,
      },
      typeComplexity: {
        typeAnnotationCount: 0,
        typeAliasCount: 0,
        interfaceCount: 0,
        genericParameterCount: 0,
        unionTypeCount: 0,
        intersectionTypeCount: 0,
        conditionalTypeCount: 0,
        typeAssertionCount: 0,
        nonNullAssertionCount: 0,
        satisfiesExpressionCount: 0,
      },
      duplication: {
        duplicateBlockCount: 2,
        duplicateBlockGroupCount: 2,
        duplicateBlockGroups: [
          [
            {
              endLine: 271,
              startLine: 251,
            },
            {
              endLine: 314,
              startLine: 294,
            },
          ],
          [
            {
              endLine: 457,
              startLine: 446,
            },
            {
              endLine: 526,
              startLine: 515,
            },
          ],
        ],
        duplicateLineCount: 48,
        duplicationRatio: 0.0894,
        maxDuplicateBlockSize: 114,
      },
      halstead: {
        distinctOperators: 23,
        distinctOperands: 280,
        totalOperators: 673,
        totalOperands: 1321,
        vocabulary: 303,
        length: 1994,
        volume: 16_436.8889,
        difficulty: 54.2554,
        effort: 891_789.2788,
        time: 49_543.8488,
        bugs: 5.479,
      },
      maintainabilityIndex: 0,
    },
    oracleFunctions: [
      ['status', 67, 73, 'cognitive', 'sonarjs', 3],
      ['status', 67, 73, 'cyclomatic', 'lizard', 5],
      ['(anonymous)', 90, 96, 'cyclomatic', 'lizard', 3],
      ['(anonymous)', 93, 95, 'cyclomatic', 'lizard', 1],
      ['send', 111, 236, 'cognitive', 'sonarjs', 39],
      ['send', 111, 236, 'cyclomatic', 'lizard', 30],
      ['json', 250, 279, 'cognitive', 'sonarjs', 5],
      ['json', 250, 279, 'cyclomatic', 'lizard', 4],
      ['jsonp', 293, 352, 'cognitive', 'sonarjs', 11],
      ['jsonp', 293, 352, 'cyclomatic', 'lizard', 9],
      ['sendStatus', 369, 376, 'cognitive', 'sonarjs', 1],
      ['sendStatus', 369, 376, 'cyclomatic', 'lizard', 2],
      ['sendFile', 419, 458, 'cyclomatic', 'lizard', 7],
      ['(anonymous)', 449, 457, 'cognitive', 'sonarjs', 5],
      ['(anonymous)', 449, 457, 'cyclomatic', 'lizard', 7],
      ['(anonymous)', 501, 527, 'cyclomatic', 'lizard', 3],
      ['(anonymous)', 518, 526, 'cognitive', 'sonarjs', 5],
      ['(anonymous)', 518, 526, 'cyclomatic', 'lizard', 7],
      ['download', 550, 599, 'cyclomatic', 'lizard', 13],
      ['contentType', 619, 625, 'cognitive', 'sonarjs', 1],
      ['contentType', 619, 625, 'cyclomatic', 'lizard', 2],
      ['(anonymous)', 684, 709, 'cognitive', 'sonarjs', 4],
      ['(anonymous)', 684, 709, 'cyclomatic', 'lizard', 4],
      ['(anonymous)', 689, 689, 'cyclomatic', 'lizard', 1],
      ['(anonymous)', 704, 704, 'cyclomatic', 'lizard', 1],
      ['attachment', 719, 727, 'cognitive', 'sonarjs', 1],
      ['attachment', 719, 727, 'cyclomatic', 'lizard', 2],
      ['append', 744, 756, 'cognitive', 'sonarjs', 6],
      ['header', 777, 801, 'cognitive', 'sonarjs', 18],
      ['header', 777, 801, 'cyclomatic', 'lizard', 8],
      ['(anonymous)', 811, 813, 'cyclomatic', 'lizard', 1],
      ['clearCookie', 824, 828, 'cyclomatic', 'lizard', 1],
      ['(anonymous)', 854, 887, 'cognitive', 'sonarjs', 8],
      ['(anonymous)', 854, 887, 'cyclomatic', 'lizard', 8],
      ['location', 906, 916, 'cognitive', 'sonarjs', 2],
      ['location', 906, 916, 'cyclomatic', 'lizard', 3],
      ['redirect', 936, 980, 'cognitive', 'sonarjs', 6],
      ['redirect', 936, 980, 'cyclomatic', 'lizard', 4],
      ['(anonymous)', 957, 959, 'cyclomatic', 'lizard', 1],
      ['(anonymous)', 961, 964, 'cyclomatic', 'lizard', 1],
      ['(anonymous)', 966, 968, 'cyclomatic', 'lizard', 1],
      ['(anonymous)', 991, 1001, 'cognitive', 'sonarjs', 3],
      ['(anonymous)', 991, 1001, 'cyclomatic', 'lizard', 4],
      ['render', 1016, 1040, 'cyclomatic', 'lizard', 4],
      ['(anonymous)', 1033, 1036, 'cognitive', 'sonarjs', 1],
      ['(anonymous)', 1033, 1036, 'cyclomatic', 'lizard', 2],
      ['sendfile', 1043, 1131, 'cyclomatic', 'lizard', 2],
      ['onaborted', 1048, 1055, 'cognitive', 'sonarjs', 1],
      ['onaborted', 1048, 1055, 'cyclomatic', 'lizard', 2],
      ['ondirectory', 1058, 1065, 'cognitive', 'sonarjs', 1],
      ['ondirectory', 1058, 1065, 'cyclomatic', 'lizard', 2],
      ['onerror', 1068, 1072, 'cognitive', 'sonarjs', 1],
      ['onerror', 1068, 1072, 'cyclomatic', 'lizard', 2],
      ['onend', 1075, 1079, 'cognitive', 'sonarjs', 1],
      ['onend', 1075, 1079, 'cyclomatic', 'lizard', 2],
      ['onfile', 1082, 1084, 'cyclomatic', 'lizard', 1],
      ['onfinish', 1087, 1102, 'cyclomatic', 'lizard', 5],
      ['(anonymous)', 1092, 1101, 'cognitive', 'sonarjs', 3],
      ['(anonymous)', 1092, 1101, 'cyclomatic', 'lizard', 4],
      ['onstream', 1105, 1107, 'cyclomatic', 'lizard', 1],
      ['headers', 1118, 1126, 'cognitive', 'sonarjs', 1],
      ['headers', 1118, 1126, 'cyclomatic', 'lizard', 2],
      ['stringify', 1145, 1169, 'cyclomatic', 'lizard', 5],
      ['(anonymous)', 1153, 1165, 'cognitive', 'sonarjs', 1],
      ['(anonymous)', 1153, 1165, 'cyclomatic', 'lizard', 4],
    ],
    knownDivergences: [
      ['(anonymous)', 90, 96, 'cognitive', 'sonarjs', 1, 2],
      ['sendFile', 419, 458, 'cognitive', 'sonarjs', 5, 14],
      ['(anonymous)', 501, 527, 'cognitive', 'sonarjs', 1, 10],
      ['download', 550, 599, 'cognitive', 'sonarjs', 14, 15],
      ['render', 1016, 1040, 'cognitive', 'sonarjs', 2, 5],
      ['sendfile', 1043, 1131, 'cognitive', 'sonarjs', 1, 26],
      ['onfinish', 1087, 1102, 'cognitive', 'sonarjs', 4, 9],
      ['stringify', 1145, 1169, 'cognitive', 'sonarjs', 4, 7],
    ],
  },
  {
    file: 'gin-1.9.1-gin.go',
    language: 'go',
    aggregates: {
      lines: {
        total: 712,
        code: 487,
        comment: 122,
        blank: 103,
      },
      functionCount: 44,
      classCount: 0,
      cyclomaticComplexity: 61,
      maxCyclomaticComplexity: 18,
      cognitiveComplexity: 82,
      maxCognitiveComplexity: 30,
      nestingDepth: 3,
      ncssCount: 360,
      callGraph: {
        callCount: 158,
        uniqueCalleeCount: 82,
        internalCallCount: 42,
        internalEdgeCount: 40,
        recursiveFunctionCount: 3,
        maxFanIn: 5,
        maxFanOut: 3,
        maxCallDepth: 3,
      },
      coupling: {
        importCount: 13,
        importSourceCount: 13,
        relativeImportCount: 0,
        externalImportCount: 13,
        exportCount: 29,
      },
      module: {
        declarations: [
          {
            exported: false,
            name: 'defaultMultipartMemory',
            startLine: 24,
          },
          {
            exported: false,
            name: 'default404Body',
            startLine: 27,
          },
          {
            exported: false,
            name: 'default405Body',
            startLine: 28,
          },
          {
            exported: false,
            name: 'defaultPlatform',
            startLine: 31,
          },
          {
            exported: false,
            name: 'defaultTrustedCIDRs',
            startLine: 33,
          },
          {
            exported: false,
            name: 'regSafePrefix',
            startLine: 44,
          },
          {
            exported: false,
            name: 'regRemoveRepeatedChar',
            startLine: 45,
          },
          {
            exported: true,
            name: 'HandlerFunc',
            startLine: 48,
          },
          {
            exported: true,
            name: 'HandlersChain',
            startLine: 51,
          },
          {
            exported: true,
            name: 'HandlersChain.Last',
            startLine: 54,
          },
          {
            exported: true,
            name: 'RouteInfo',
            startLine: 62,
          },
          {
            exported: true,
            name: 'RoutesInfo',
            startLine: 70,
          },
          {
            exported: true,
            name: 'PlatformGoogleAppEngine',
            startLine: 76,
          },
          {
            exported: true,
            name: 'PlatformCloudflare',
            startLine: 79,
          },
          {
            exported: true,
            name: 'Engine',
            startLine: 84,
          },
          {
            exported: false,
            name: '_',
            startLine: 173,
          },
          {
            exported: true,
            name: 'New',
            startLine: 183,
          },
          {
            exported: true,
            name: 'Default',
            startLine: 216,
          },
          {
            exported: true,
            name: 'Engine.Handler',
            startLine: 223,
          },
          {
            exported: false,
            name: 'Engine.allocateContext',
            startLine: 232,
          },
          {
            exported: true,
            name: 'Engine.Delims',
            startLine: 239,
          },
          {
            exported: true,
            name: 'Engine.SecureJsonPrefix',
            startLine: 245,
          },
          {
            exported: true,
            name: 'Engine.LoadHTMLGlob',
            startLine: 252,
          },
          {
            exported: true,
            name: 'Engine.LoadHTMLFiles',
            startLine: 268,
          },
          {
            exported: true,
            name: 'Engine.SetHTMLTemplate',
            startLine: 279,
          },
          {
            exported: true,
            name: 'Engine.SetFuncMap',
            startLine: 288,
          },
          {
            exported: true,
            name: 'Engine.NoRoute',
            startLine: 293,
          },
          {
            exported: true,
            name: 'Engine.NoMethod',
            startLine: 299,
          },
          {
            exported: true,
            name: 'Engine.Use',
            startLine: 307,
          },
          {
            exported: false,
            name: 'Engine.rebuild404Handlers',
            startLine: 314,
          },
          {
            exported: false,
            name: 'Engine.rebuild405Handlers',
            startLine: 318,
          },
          {
            exported: false,
            name: 'Engine.addRoute',
            startLine: 322,
          },
          {
            exported: true,
            name: 'Engine.Routes',
            startLine: 349,
          },
          {
            exported: false,
            name: 'iterate',
            startLine: 356,
          },
          {
            exported: true,
            name: 'Engine.Run',
            startLine: 376,
          },
          {
            exported: false,
            name: 'Engine.prepareTrustedCIDRs',
            startLine: 390,
          },
          {
            exported: true,
            name: 'Engine.SetTrustedProxies',
            startLine: 427,
          },
          {
            exported: false,
            name: 'Engine.isUnsafeTrustedProxies',
            startLine: 433,
          },
          {
            exported: false,
            name: 'Engine.parseTrustedProxies',
            startLine: 438,
          },
          {
            exported: false,
            name: 'Engine.isTrustedProxy',
            startLine: 445,
          },
          {
            exported: false,
            name: 'Engine.validateHeader',
            startLine: 458,
          },
          {
            exported: false,
            name: 'parseIP',
            startLine: 481,
          },
          {
            exported: true,
            name: 'Engine.RunTLS',
            startLine: 496,
          },
          {
            exported: true,
            name: 'Engine.RunUnix',
            startLine: 512,
          },
          {
            exported: true,
            name: 'Engine.RunFd',
            startLine: 535,
          },
          {
            exported: true,
            name: 'Engine.RunListener',
            startLine: 556,
          },
          {
            exported: true,
            name: 'Engine.ServeHTTP',
            startLine: 570,
          },
          {
            exported: true,
            name: 'Engine.HandleContext',
            startLine: 584,
          },
          {
            exported: false,
            name: 'Engine.handleHTTPRequest',
            startLine: 592,
          },
          {
            exported: false,
            name: 'mimePlain',
            startLine: 652,
          },
          {
            exported: false,
            name: 'serveError',
            startLine: 654,
          },
          {
            exported: false,
            name: 'redirectTrailingSlash',
            startLine: 671,
          },
          {
            exported: false,
            name: 'redirectFixedPath',
            startLine: 687,
          },
          {
            exported: false,
            name: 'redirectRequest',
            startLine: 699,
          },
        ],
        importSources: [
          'fmt',
          'html/template',
          'net',
          'net/http',
          'os',
          'path',
          'regexp',
          'strings',
          'sync',
          'github.com/gin-gonic/gin/internal/bytesconv',
          'github.com/gin-gonic/gin/render',
          'golang.org/x/net/http2',
          'golang.org/x/net/http2/h2c',
        ],
      },
      cohesion: {
        averageFunctionIdentifierOverlap: 0.0666,
        sharedIdentifierCount: 100,
        uniqueIdentifierCount: 234,
      },
      syntaxFeatures: {
        assignmentCount: 102,
        awaitExpressionCount: 0,
        loopStatementCount: 7,
        mutableBindingCount: 7,
        returnStatementCount: 45,
        throwStatementCount: 0,
        tryStatementCount: 0,
      },
      typeComplexity: {
        typeAnnotationCount: 0,
        typeAliasCount: 0,
        interfaceCount: 0,
        genericParameterCount: 0,
        unionTypeCount: 0,
        intersectionTypeCount: 0,
        conditionalTypeCount: 0,
        typeAssertionCount: 0,
        nonNullAssertionCount: 0,
        satisfiesExpressionCount: 0,
      },
      // Near-miss (Type-3) clones: RunTLS/RunListener and RunUnix/RunFd share the same
      // debugPrint + trusted-proxy warning + serve boilerplate with small edits.
      duplication: {
        duplicateBlockCount: 2,
        duplicateBlockGroupCount: 2,
        duplicateBlockGroups: [
          [
            { startLine: 496, endLine: 507 },
            { startLine: 556, endLine: 567 },
          ],
          [
            { startLine: 512, endLine: 530 },
            { startLine: 535, endLine: 552 },
          ],
        ],
        duplicateLineCount: 52,
        duplicationRatio: 0.1068,
        maxDuplicateBlockSize: 97,
      },
      halstead: {
        distinctOperators: 23,
        distinctOperands: 333,
        totalOperators: 553,
        totalOperands: 1300,
        vocabulary: 356,
        length: 1853,
        volume: 15_705.534,
        difficulty: 44.8949,
        effort: 705_098.3003,
        time: 39_172.1278,
        bugs: 5.2352,
      },
      maintainabilityIndex: 3.7888,
    },
    oracleFunctions: [
      ['Last', 54, 59, 'cognitive', 'gocognit', 1],
      ['Last', 54, 59, 'cyclomatic', 'lizard', 2],
      ['New', 183, 213, 'cognitive', 'gocognit', 0],
      ['New', 183, 213, 'cyclomatic', 'lizard', 1],
      ['(anonymous)', 209, 211, 'cyclomatic', 'lizard', 1],
      ['Default', 216, 221, 'cognitive', 'gocognit', 0],
      ['Default', 216, 221, 'cyclomatic', 'lizard', 1],
      ['Handler', 223, 230, 'cognitive', 'gocognit', 1],
      ['Handler', 223, 230, 'cyclomatic', 'lizard', 2],
      ['allocateContext', 232, 236, 'cognitive', 'gocognit', 0],
      ['allocateContext', 232, 236, 'cyclomatic', 'lizard', 1],
      ['Delims', 239, 242, 'cognitive', 'gocognit', 0],
      ['Delims', 239, 242, 'cyclomatic', 'lizard', 1],
      ['SecureJsonPrefix', 245, 248, 'cognitive', 'gocognit', 0],
      ['SecureJsonPrefix', 245, 248, 'cyclomatic', 'lizard', 1],
      ['LoadHTMLGlob', 252, 264, 'cognitive', 'gocognit', 1],
      ['LoadHTMLGlob', 252, 264, 'cyclomatic', 'lizard', 2],
      ['LoadHTMLFiles', 268, 276, 'cognitive', 'gocognit', 1],
      ['LoadHTMLFiles', 268, 276, 'cyclomatic', 'lizard', 2],
      ['SetHTMLTemplate', 279, 285, 'cognitive', 'gocognit', 1],
      ['SetHTMLTemplate', 279, 285, 'cyclomatic', 'lizard', 2],
      ['SetFuncMap', 288, 290, 'cognitive', 'gocognit', 0],
      ['SetFuncMap', 288, 290, 'cyclomatic', 'lizard', 1],
      ['NoRoute', 293, 296, 'cognitive', 'gocognit', 0],
      ['NoRoute', 293, 296, 'cyclomatic', 'lizard', 1],
      ['NoMethod', 299, 302, 'cognitive', 'gocognit', 0],
      ['NoMethod', 299, 302, 'cyclomatic', 'lizard', 1],
      ['Use', 307, 312, 'cognitive', 'gocognit', 0],
      ['Use', 307, 312, 'cyclomatic', 'lizard', 1],
      ['rebuild404Handlers', 314, 316, 'cognitive', 'gocognit', 0],
      ['rebuild404Handlers', 314, 316, 'cyclomatic', 'lizard', 1],
      ['rebuild405Handlers', 318, 320, 'cognitive', 'gocognit', 0],
      ['rebuild405Handlers', 318, 320, 'cyclomatic', 'lizard', 1],
      ['addRoute', 322, 345, 'cognitive', 'gocognit', 3],
      ['addRoute', 322, 345, 'cyclomatic', 'lizard', 4],
      ['Routes', 349, 354, 'cognitive', 'gocognit', 1],
      ['Routes', 349, 354, 'cyclomatic', 'lizard', 2],
      ['iterate', 356, 371, 'cyclomatic', 'lizard', 3],
      ['Run', 376, 388, 'cognitive', 'gocognit', 1],
      ['Run', 376, 388, 'cyclomatic', 'lizard', 2],
      ['(anonymous)', 377, 377, 'cyclomatic', 'lizard', 1],
      ['prepareTrustedCIDRs', 390, 417, 'cognitive', 'gocognit', 12],
      ['prepareTrustedCIDRs', 390, 417, 'cyclomatic', 'lizard', 8],
      ['SetTrustedProxies', 427, 430, 'cognitive', 'gocognit', 0],
      ['SetTrustedProxies', 427, 430, 'cyclomatic', 'lizard', 1],
      ['isUnsafeTrustedProxies', 433, 435, 'cognitive', 'gocognit', 1],
      ['isUnsafeTrustedProxies', 433, 435, 'cyclomatic', 'lizard', 2],
      ['parseTrustedProxies', 438, 442, 'cognitive', 'gocognit', 0],
      ['parseTrustedProxies', 438, 442, 'cyclomatic', 'lizard', 1],
      ['isTrustedProxy', 445, 455, 'cognitive', 'gocognit', 4],
      ['isTrustedProxy', 445, 455, 'cyclomatic', 'lizard', 4],
      ['validateHeader', 458, 477, 'cognitive', 'gocognit', 7],
      ['validateHeader', 458, 477, 'cyclomatic', 'lizard', 6],
      ['parseIP', 481, 491, 'cognitive', 'gocognit', 1],
      ['parseIP', 481, 491, 'cyclomatic', 'lizard', 2],
      ['RunTLS', 496, 507, 'cognitive', 'gocognit', 1],
      ['RunTLS', 496, 507, 'cyclomatic', 'lizard', 2],
      ['(anonymous)', 498, 498, 'cyclomatic', 'lizard', 1],
      ['RunUnix', 512, 530, 'cognitive', 'gocognit', 2],
      ['RunUnix', 512, 530, 'cyclomatic', 'lizard', 3],
      ['(anonymous)', 514, 514, 'cyclomatic', 'lizard', 1],
      ['RunFd', 535, 552, 'cognitive', 'gocognit', 2],
      ['RunFd', 535, 552, 'cyclomatic', 'lizard', 3],
      ['(anonymous)', 537, 537, 'cyclomatic', 'lizard', 1],
      ['RunListener', 556, 567, 'cognitive', 'gocognit', 1],
      ['RunListener', 556, 567, 'cyclomatic', 'lizard', 2],
      ['(anonymous)', 558, 558, 'cyclomatic', 'lizard', 1],
      ['ServeHTTP', 570, 579, 'cognitive', 'gocognit', 0],
      ['ServeHTTP', 570, 579, 'cyclomatic', 'lizard', 1],
      ['HandleContext', 584, 590, 'cognitive', 'gocognit', 0],
      ['HandleContext', 584, 590, 'cyclomatic', 'lizard', 1],
      ['handleHTTPRequest', 592, 650, 'cognitive', 'gocognit', 30],
      ['handleHTTPRequest', 592, 650, 'cyclomatic', 'lizard', 18],
      ['serveError', 654, 669, 'cognitive', 'gocognit', 4],
      ['serveError', 654, 669, 'cyclomatic', 'lizard', 4],
      ['redirectTrailingSlash', 671, 685, 'cognitive', 'gocognit', 3],
      ['redirectTrailingSlash', 671, 685, 'cyclomatic', 'lizard', 4],
      ['redirectFixedPath', 687, 697, 'cognitive', 'gocognit', 1],
      ['redirectFixedPath', 687, 697, 'cyclomatic', 'lizard', 2],
      ['redirectRequest', 699, 711, 'cognitive', 'gocognit', 1],
      ['redirectRequest', 699, 711, 'cyclomatic', 'lizard', 2],
    ],
    knownDivergences: [['iterate', 356, 371, 'cognitive', 'gocognit', 3, 2]],
  },
  {
    file: 'guava-33.0.0-Joiner.java',
    language: 'java',
    aggregates: {
      lines: {
        total: 519,
        code: 256,
        comment: 218,
        blank: 45,
      },
      functionCount: 41,
      classCount: 5,
      cyclomaticComplexity: 21,
      maxCyclomaticComplexity: 5,
      cognitiveComplexity: 23,
      maxCognitiveComplexity: 10,
      nestingDepth: 2,
      ncssCount: 150,
      callGraph: {
        callCount: 103,
        uniqueCalleeCount: 23,
        internalCallCount: 7,
        internalEdgeCount: 6,
        recursiveFunctionCount: 0,
        maxFanIn: 3,
        maxFanOut: 1,
        maxCallDepth: 1,
      },
      coupling: {
        importCount: 13,
        importSourceCount: 13,
        relativeImportCount: 0,
        externalImportCount: 13,
        exportCount: 0,
      },
      module: {
        declarations: [
          {
            exported: false,
            name: 'com.google.common.base::Joiner',
            startLine: 67,
          },
        ],
        importSources: [
          'com.google.common.base.Preconditions.checkNotNull',
          'java.util.Objects.requireNonNull',
          'com.google.common.annotations.GwtCompatible',
          'com.google.errorprone.annotations.CanIgnoreReturnValue',
          'java.io.IOException',
          'java.util.AbstractList',
          'java.util.Arrays',
          'java.util.Iterator',
          'java.util.List',
          'java.util.Map',
          'java.util.Map.Entry',
          'javax.annotation.CheckForNull',
          'org.checkerframework.checker.nullness.qual.Nullable',
        ],
      },
      cohesion: {
        averageFunctionIdentifierOverlap: 0.0951,
        sharedIdentifierCount: 44,
        uniqueIdentifierCount: 51,
      },
      syntaxFeatures: {
        assignmentCount: 4,
        awaitExpressionCount: 0,
        loopStatementCount: 4,
        mutableBindingCount: 7,
        returnStatementCount: 36,
        throwStatementCount: 6,
        tryStatementCount: 2,
      },
      typeComplexity: {
        typeAnnotationCount: 0,
        typeAliasCount: 0,
        interfaceCount: 0,
        genericParameterCount: 8,
        unionTypeCount: 0,
        intersectionTypeCount: 0,
        conditionalTypeCount: 0,
        typeAssertionCount: 0,
        nonNullAssertionCount: 0,
        satisfiesExpressionCount: 0,
      },
      duplication: {
        duplicateBlockCount: 2,
        duplicateBlockGroupCount: 2,
        duplicateBlockGroups: [
          // Near-miss (Type-3) clone: Joiner's first-element and remaining-elements `while
          // (parts.hasNext())` loops differ only in the `break` and the separator append.
          [
            {
              endLine: 282,
              startLine: 276,
            },
            {
              endLine: 289,
              startLine: 283,
            },
          ],
          [
            {
              endLine: 395,
              startLine: 392,
            },
            {
              endLine: 401,
              startLine: 398,
            },
          ],
        ],
        duplicateLineCount: 22,
        duplicationRatio: 0.0859,
        maxDuplicateBlockSize: 53,
      },
      halstead: {
        distinctOperators: 15,
        distinctOperands: 95,
        totalOperators: 265,
        totalOperands: 650,
        vocabulary: 110,
        length: 915,
        volume: 6204.9441,
        difficulty: 51.3158,
        effort: 318_411.6071,
        time: 17_689.5337,
        bugs: 2.0683,
      },
      maintainabilityIndex: 18.0854,
    },
    oracleFunctions: [
      ['on', 71, 73, 'cognitive', 'pmd', 0],
      ['on', 71, 73, 'cyclomatic', 'lizard', 1],
      ['on', 71, 73, 'cyclomatic', 'pmd', 1],
      ['on', 71, 73, 'ncss', 'pmd', 2],
      ['on', 76, 78, 'cognitive', 'pmd', 0],
      ['on', 76, 78, 'cyclomatic', 'lizard', 1],
      ['on', 76, 78, 'cyclomatic', 'pmd', 1],
      ['on', 76, 78, 'ncss', 'pmd', 2],
      ['Joiner', 82, 84, 'cognitive', 'pmd', 0],
      ['Joiner', 82, 84, 'cyclomatic', 'lizard', 1],
      ['Joiner', 82, 84, 'cyclomatic', 'pmd', 1],
      ['Joiner', 82, 84, 'ncss', 'pmd', 2],
      ['Joiner', 86, 88, 'cognitive', 'pmd', 0],
      ['Joiner', 86, 88, 'cyclomatic', 'lizard', 1],
      ['Joiner', 86, 88, 'cyclomatic', 'pmd', 1],
      ['Joiner', 86, 88, 'ncss', 'pmd', 2],
      ['appendTo', 100, 104, 'cognitive', 'pmd', 0],
      ['appendTo', 100, 104, 'cyclomatic', 'lizard', 1],
      ['appendTo', 100, 104, 'cyclomatic', 'pmd', 1],
      ['appendTo', 100, 104, 'ncss', 'pmd', 2],
      ['appendTo', 112, 124, 'cognitive', 'pmd', 3],
      ['appendTo', 112, 124, 'cyclomatic', 'lizard', 3],
      ['appendTo', 112, 124, 'cyclomatic', 'pmd', 3],
      ['appendTo', 112, 124, 'ncss', 'pmd', 8],
      ['appendTo', 130, 136, 'cognitive', 'pmd', 0],
      ['appendTo', 130, 136, 'cyclomatic', 'lizard', 1],
      ['appendTo', 130, 136, 'cyclomatic', 'pmd', 1],
      ['appendTo', 130, 136, 'ncss', 'pmd', 3],
      ['appendTo', 139, 147, 'cognitive', 'pmd', 0],
      ['appendTo', 139, 147, 'cyclomatic', 'lizard', 1],
      ['appendTo', 139, 147, 'cyclomatic', 'pmd', 1],
      ['appendTo', 139, 147, 'ncss', 'pmd', 2],
      ['appendTo', 154, 158, 'cognitive', 'pmd', 0],
      ['appendTo', 154, 158, 'cyclomatic', 'lizard', 1],
      ['appendTo', 154, 158, 'cyclomatic', 'pmd', 1],
      ['appendTo', 154, 158, 'ncss', 'pmd', 2],
      ['appendTo', 167, 176, 'cognitive', 'pmd', 1],
      ['appendTo', 167, 176, 'cyclomatic', 'pmd', 3],
      ['appendTo', 167, 176, 'ncss', 'pmd', 5],
      ['appendTo', 183, 188, 'cognitive', 'pmd', 0],
      ['appendTo', 183, 188, 'cyclomatic', 'lizard', 1],
      ['appendTo', 183, 188, 'cyclomatic', 'pmd', 1],
      ['appendTo', 183, 188, 'ncss', 'pmd', 3],
      ['appendTo', 195, 202, 'cognitive', 'pmd', 0],
      ['appendTo', 195, 202, 'cyclomatic', 'lizard', 1],
      ['appendTo', 195, 202, 'cyclomatic', 'pmd', 1],
      ['appendTo', 195, 202, 'ncss', 'pmd', 2],
      ['join', 208, 210, 'cognitive', 'pmd', 0],
      ['join', 208, 210, 'cyclomatic', 'lizard', 1],
      ['join', 208, 210, 'cyclomatic', 'pmd', 1],
      ['join', 208, 210, 'ncss', 'pmd', 2],
      ['join', 218, 220, 'cognitive', 'pmd', 0],
      ['join', 218, 220, 'cyclomatic', 'lizard', 1],
      ['join', 218, 220, 'cyclomatic', 'pmd', 1],
      ['join', 218, 220, 'ncss', 'pmd', 2],
      ['join', 226, 230, 'cognitive', 'pmd', 0],
      ['join', 226, 230, 'cyclomatic', 'lizard', 1],
      ['join', 226, 230, 'cyclomatic', 'pmd', 1],
      ['join', 226, 230, 'ncss', 'pmd', 3],
      ['join', 236, 239, 'cognitive', 'pmd', 0],
      ['join', 236, 239, 'cyclomatic', 'lizard', 1],
      ['join', 236, 239, 'cyclomatic', 'pmd', 1],
      ['join', 236, 239, 'ncss', 'pmd', 2],
      ['useForNull', 245, 263, 'cognitive', 'pmd', 2],
      ['useForNull', 245, 263, 'cyclomatic', 'lizard', 1],
      ['useForNull', 245, 263, 'cyclomatic', 'pmd', 1],
      ['toString', 248, 251, 'cognitive', 'pmd', 1],
      ['toString', 248, 251, 'cyclomatic', 'lizard', 2],
      ['toString', 248, 251, 'cyclomatic', 'pmd', 2],
      ['toString', 248, 251, 'ncss', 'pmd', 2],
      ['useForNull', 253, 256, 'cognitive', 'pmd', 0],
      ['useForNull', 253, 256, 'cyclomatic', 'pmd', 2],
      ['useForNull', 253, 256, 'ncss', 'pmd', 2],
      ['skipNulls', 258, 261, 'cognitive', 'pmd', 0],
      ['skipNulls', 258, 261, 'cyclomatic', 'pmd', 2],
      ['skipNulls', 258, 261, 'ncss', 'pmd', 2],
      ['skipNulls', 269, 303, 'cognitive', 'pmd', 10],
      ['skipNulls', 269, 303, 'cyclomatic', 'lizard', 1],
      ['skipNulls', 269, 303, 'cyclomatic', 'pmd', 1],
      ['appendTo', 271, 291, 'cognitive', 'pmd', 6],
      ['appendTo', 271, 291, 'cyclomatic', 'lizard', 5],
      ['appendTo', 271, 291, 'cyclomatic', 'pmd', 5],
      ['appendTo', 271, 291, 'ncss', 'pmd', 14],
      ['useForNull', 293, 296, 'cognitive', 'pmd', 0],
      ['useForNull', 293, 296, 'cyclomatic', 'pmd', 2],
      ['useForNull', 293, 296, 'ncss', 'pmd', 2],
      ['withKeyValueSeparator', 298, 301, 'cognitive', 'pmd', 0],
      ['withKeyValueSeparator', 298, 301, 'cyclomatic', 'pmd', 2],
      ['withKeyValueSeparator', 298, 301, 'ncss', 'pmd', 2],
      ['withKeyValueSeparator', 311, 313, 'cognitive', 'pmd', 0],
      ['withKeyValueSeparator', 311, 313, 'cyclomatic', 'lizard', 1],
      ['withKeyValueSeparator', 311, 313, 'cyclomatic', 'pmd', 1],
      ['withKeyValueSeparator', 311, 313, 'ncss', 'pmd', 2],
      ['withKeyValueSeparator', 319, 321, 'cognitive', 'pmd', 0],
      ['withKeyValueSeparator', 319, 321, 'cyclomatic', 'lizard', 1],
      ['withKeyValueSeparator', 319, 321, 'cyclomatic', 'pmd', 1],
      ['withKeyValueSeparator', 319, 321, 'ncss', 'pmd', 2],
      ['MapJoiner', 345, 348, 'cognitive', 'pmd', 0],
      ['MapJoiner', 345, 348, 'cyclomatic', 'lizard', 1],
      ['MapJoiner', 345, 348, 'cyclomatic', 'pmd', 1],
      ['MapJoiner', 345, 348, 'ncss', 'pmd', 3],
      ['appendTo', 354, 357, 'cognitive', 'pmd', 0],
      ['appendTo', 354, 357, 'cyclomatic', 'lizard', 1],
      ['appendTo', 354, 357, 'cyclomatic', 'pmd', 1],
      ['appendTo', 354, 357, 'ncss', 'pmd', 2],
      ['appendTo', 364, 367, 'cognitive', 'pmd', 0],
      ['appendTo', 364, 367, 'cyclomatic', 'lizard', 1],
      ['appendTo', 364, 367, 'cyclomatic', 'pmd', 1],
      ['appendTo', 364, 367, 'ncss', 'pmd', 2],
      ['appendTo', 375, 379, 'cognitive', 'pmd', 0],
      ['appendTo', 375, 379, 'cyclomatic', 'lizard', 1],
      ['appendTo', 375, 379, 'cyclomatic', 'pmd', 1],
      ['appendTo', 375, 379, 'ncss', 'pmd', 2],
      ['appendTo', 387, 405, 'cognitive', 'pmd', 3],
      ['appendTo', 387, 405, 'cyclomatic', 'lizard', 3],
      ['appendTo', 387, 405, 'cyclomatic', 'pmd', 3],
      ['appendTo', 387, 405, 'ncss', 'pmd', 14],
      ['appendTo', 414, 417, 'cognitive', 'pmd', 0],
      ['appendTo', 414, 417, 'cyclomatic', 'lizard', 1],
      ['appendTo', 414, 417, 'cyclomatic', 'pmd', 1],
      ['appendTo', 414, 417, 'ncss', 'pmd', 2],
      ['appendTo', 426, 434, 'cognitive', 'pmd', 1],
      ['appendTo', 426, 434, 'cyclomatic', 'pmd', 3],
      ['appendTo', 426, 434, 'ncss', 'pmd', 5],
      ['join', 440, 442, 'cognitive', 'pmd', 0],
      ['join', 440, 442, 'cyclomatic', 'lizard', 1],
      ['join', 440, 442, 'cyclomatic', 'pmd', 1],
      ['join', 440, 442, 'ncss', 'pmd', 2],
      ['join', 450, 452, 'cognitive', 'pmd', 0],
      ['join', 450, 452, 'cyclomatic', 'lizard', 1],
      ['join', 450, 452, 'cyclomatic', 'pmd', 1],
      ['join', 450, 452, 'ncss', 'pmd', 2],
      ['join', 460, 462, 'cognitive', 'pmd', 0],
      ['join', 460, 462, 'cyclomatic', 'lizard', 1],
      ['join', 460, 462, 'cyclomatic', 'pmd', 1],
      ['join', 460, 462, 'ncss', 'pmd', 2],
      ['useForNull', 468, 470, 'cognitive', 'pmd', 0],
      ['useForNull', 468, 470, 'cyclomatic', 'lizard', 1],
      ['useForNull', 468, 470, 'cyclomatic', 'pmd', 1],
      ['useForNull', 468, 470, 'ncss', 'pmd', 2],
      ['toString', 473, 493, 'cognitive', 'pmd', 1],
      ['toString', 473, 493, 'cyclomatic', 'lizard', 2],
      ['toString', 473, 493, 'cyclomatic', 'pmd', 2],
      ['toString', 473, 493, 'ncss', 'pmd', 3],
      ['iterable', 495, 517, 'cognitive', 'pmd', 2],
      ['iterable', 495, 517, 'cyclomatic', 'pmd', 1],
      ['size', 499, 502, 'cognitive', 'pmd', 0],
      ['size', 499, 502, 'cyclomatic', 'pmd', 1],
      ['size', 499, 502, 'ncss', 'pmd', 2],
      ['get', 504, 515, 'cognitive', 'pmd', 1],
      ['get', 504, 515, 'cyclomatic', 'pmd', 3],
      ['get', 504, 515, 'ncss', 'pmd', 8],
    ],
    knownDivergences: [
      ['appendTo', 167, 176, 'cyclomatic', 'lizard', 2, 3],
      ['useForNull', 245, 263, 'ncss', 'pmd', 3, 9],
      ['useForNull', 253, 256, 'cyclomatic', 'lizard', 1, 2],
      ['skipNulls', 258, 261, 'cyclomatic', 'lizard', 1, 2],
      ['skipNulls', 269, 303, 'ncss', 'pmd', 2, 20],
      ['useForNull', 293, 296, 'cyclomatic', 'lizard', 1, 2],
      ['withKeyValueSeparator', 298, 301, 'cyclomatic', 'lizard', 1, 2],
      ['appendTo', 426, 434, 'cyclomatic', 'lizard', 2, 3],
      ['iterable', 495, 517, 'cyclomatic', 'lizard', 3, 1],
      ['iterable', 495, 517, 'ncss', 'pmd', 3, 13],
    ],
  },
  {
    file: 'mattermost-5.39.0-login_controller.jsx',
    language: 'jsx',
    aggregates: {
      lines: {
        total: 886,
        code: 784,
        comment: 20,
        blank: 82,
      },
      functionCount: 24,
      classCount: 1,
      cyclomaticComplexity: 94,
      maxCyclomaticComplexity: 25,
      cognitiveComplexity: 111,
      maxCognitiveComplexity: 22,
      nestingDepth: 2,
      ncssCount: 283,
      callGraph: {
        callCount: 119,
        uniqueCalleeCount: 41,
        internalCallCount: 0,
        internalEdgeCount: 0,
        recursiveFunctionCount: 0,
        maxFanIn: 0,
        maxFanOut: 0,
        maxCallDepth: 0,
      },
      coupling: {
        importCount: 26,
        importSourceCount: 26,
        relativeImportCount: 1,
        externalImportCount: 25,
        exportCount: 1,
      },
      module: {
        declarations: [
          {
            exported: false,
            name: 'LoginController',
            startLine: 37,
          },
        ],
        importSources: [
          'prop-types',
          'react',
          'react-intl',
          'react-router-dom',
          'mattermost-redux/client',
          'actions/global_actions',
          'stores/local_storage_store',
          'utils/browser_history',
          'utils/constants.jsx',
          'utils/react_intl',
          'utils/utils.jsx',
          'utils/notifications',
          'utils/i18n.jsx',
          'images/logo.png',
          'components/common/site_name_and_description',
          'components/announcement_bar',
          'components/form_error',
          'components/formatted_markdown_message.jsx',
          'components/common/back_button',
          'components/loading_screen',
          'components/widgets/loading/loading_wrapper',
          'components/widgets/icons/fa_success_icon',
          'components/widgets/icons/fa_warning_icon',
          'components/localized_input/localized_input',
          'components/markdown',
          '../login_mfa.jsx',
        ],
      },
      cohesion: {
        averageFunctionIdentifierOverlap: 0.0543,
        sharedIdentifierCount: 86,
        uniqueIdentifierCount: 205,
      },
      syntaxFeatures: {
        assignmentCount: 24,
        awaitExpressionCount: 1,
        loopStatementCount: 0,
        mutableBindingCount: 10,
        returnStatementCount: 21,
        throwStatementCount: 0,
        tryStatementCount: 0,
      },
      typeComplexity: {
        typeAnnotationCount: 0,
        typeAliasCount: 0,
        interfaceCount: 0,
        genericParameterCount: 0,
        unionTypeCount: 0,
        intersectionTypeCount: 0,
        conditionalTypeCount: 0,
        typeAssertionCount: 0,
        nonNullAssertionCount: 0,
        satisfiesExpressionCount: 0,
      },
      duplication: {
        duplicateBlockCount: 4,
        duplicateBlockGroupCount: 3,
        duplicateBlockGroups: [
          // Near-miss (Type-3) clones: the loginId/password input-sync blocks, and the two
          // copy-pasted form-group JSX elements (input vs LocalizedInput).
          [
            {
              endLine: 205,
              startLine: 200,
            },
            {
              endLine: 213,
              startLine: 208,
            },
          ],
          [
            {
              endLine: 578,
              startLine: 564,
            },
            {
              endLine: 591,
              startLine: 578,
            },
          ],
          [
            {
              endLine: 700,
              startLine: 681,
            },
            {
              endLine: 721,
              startLine: 702,
            },
            {
              endLine: 742,
              startLine: 723,
            },
          ],
        ],
        duplicateLineCount: 100,
        duplicationRatio: 0.1276,
        maxDuplicateBlockSize: 74,
      },
      halstead: {
        distinctOperators: 27,
        distinctOperands: 395,
        totalOperators: 925,
        totalOperands: 1444,
        vocabulary: 422,
        length: 2369,
        volume: 20_660.284,
        difficulty: 49.3519,
        effort: 1_019_624.2427,
        time: 56_645.7913,
        bugs: 6.8868,
      },
      maintainabilityIndex: 0,
    },
    oracleFunctions: [
      ['constructor', 70, 93, 'cognitive', 'sonarjs', 4],
      ['componentDidMount', 95, 130, 'cognitive', 'sonarjs', 7],
      ['componentWillUnmount', 137, 142, 'cognitive', 'sonarjs', 1],
      ['(anonymous)', 144, 155, 'cognitive', 'sonarjs', 2],
      ['(anonymous)', 144, 155, 'cyclomatic', 'lizard', 2],
      ['(anonymous)', 167, 173, 'cognitive', 'sonarjs', 1],
      ['(anonymous)', 167, 173, 'cyclomatic', 'lizard', 2],
      ['(anonymous)', 174, 176, 'cyclomatic', 'lizard', 1],
      ['(anonymous)', 176, 178, 'cyclomatic', 'lizard', 1],
      ['(anonymous)', 185, 265, 'cognitive', 'sonarjs', 16],
      ['(anonymous)', 267, 323, 'cyclomatic', 'lizard', 1],
      ['(anonymous)', 270, 322, 'cyclomatic', 'lizard', 14],
      ['(anonymous)', 325, 344, 'cognitive', 'sonarjs', 5],
      ['(anonymous)', 346, 350, 'cyclomatic', 'lizard', 1],
      ['(anonymous)', 352, 356, 'cyclomatic', 'lizard', 1],
      ['(anonymous)', 358, 360, 'cyclomatic', 'lizard', 1],
      ['(anonymous)', 362, 390, 'cyclomatic', 'lizard', 4],
      ['(anonymous)', 392, 423, 'cognitive', 'sonarjs', 8],
      ['(anonymous)', 392, 423, 'cyclomatic', 'lizard', 7],
      ['(anonymous)', 425, 433, 'cognitive', 'sonarjs', 1],
      ['(anonymous)', 425, 433, 'cyclomatic', 'lizard', 7],
      ['(anonymous)', 435, 438, 'cyclomatic', 'lizard', 1],
      ['(anonymous)', 440, 535, 'cognitive', 'sonarjs', 7],
      ['(anonymous)', 537, 816, 'cognitive', 'sonarjs', 22],
      ['render', 822, 882, 'cognitive', 'sonarjs', 5],
    ],
    knownDivergences: [
      ['constructor', 70, 93, 'cyclomatic', 'lizard', 3, 5],
      ['(anonymous)', 157, 183, 'cognitive', 'sonarjs', 4, 7],
      ['(anonymous)', 157, 183, 'cyclomatic', 'lizard', 6, 5],
      ['(anonymous)', 185, 265, 'cyclomatic', 'lizard', 10, 12],
      ['(anonymous)', 270, 322, 'cognitive', 'sonarjs', 16, 18],
      ['(anonymous)', 325, 344, 'cyclomatic', 'lizard', 3, 5],
      ['(anonymous)', 362, 390, 'cognitive', 'sonarjs', 3, 4],
      ['(anonymous)', 440, 535, 'cyclomatic', 'lizard', 1, 8],
    ],
  },
  {
    file: 'nextjs-14.0.4-image-component.tsx',
    language: 'tsx',
    aggregates: {
      lines: {
        total: 417,
        code: 352,
        comment: 41,
        blank: 24,
      },
      functionCount: 20,
      classCount: 0,
      cyclomaticComplexity: 45,
      maxCyclomaticComplexity: 20,
      cognitiveComplexity: 82,
      maxCognitiveComplexity: 48,
      nestingDepth: 4,
      ncssCount: 119,
      callGraph: {
        callCount: 57,
        uniqueCalleeCount: 37,
        internalCallCount: 4,
        internalEdgeCount: 4,
        recursiveFunctionCount: 0,
        maxFanIn: 2,
        maxFanOut: 1,
        maxCallDepth: 1,
      },
      coupling: {
        importCount: 11,
        importSourceCount: 9,
        relativeImportCount: 6,
        externalImportCount: 3,
        exportCount: 5,
      },
      module: {
        declarations: [
          {
            exported: false,
            name: 'configEnv',
            startLine: 36,
          },
          {
            exported: true,
            name: 'ImageLoader',
            startLine: 43,
          },
          {
            exported: false,
            name: 'ImgElementWithDataProp',
            startLine: 45,
          },
          {
            exported: false,
            name: 'ImageElementProps',
            startLine: 49,
          },
          {
            exported: false,
            name: 'handleLoading',
            startLine: 60,
          },
          {
            exported: false,
            name: 'getDynamicProps',
            startLine: 163,
          },
          {
            exported: false,
            name: 'ImageElement',
            startLine: 180,
          },
          {
            exported: false,
            name: 'ImagePreload',
            startLine: 307,
          },
          {
            exported: true,
            name: 'Image',
            startLine: 355,
          },
        ],
        importSources: [
          'react',
          'react-dom',
          '../shared/lib/head',
          '../shared/lib/get-img-props',
          '../shared/lib/image-config',
          '../shared/lib/image-config-context.shared-runtime',
          '../shared/lib/utils/warn-once',
          '../shared/lib/router-context.shared-runtime',
          'next/dist/shared/lib/image-loader',
        ],
      },
      cohesion: {
        averageFunctionIdentifierOverlap: 0.0482,
        sharedIdentifierCount: 79,
        uniqueIdentifierCount: 131,
      },
      syntaxFeatures: {
        assignmentCount: 8,
        awaitExpressionCount: 0,
        loopStatementCount: 0,
        mutableBindingCount: 3,
        returnStatementCount: 10,
        throwStatementCount: 0,
        tryStatementCount: 0,
      },
      typeComplexity: {
        typeAnnotationCount: 23,
        typeAliasCount: 3,
        interfaceCount: 0,
        genericParameterCount: 0,
        unionTypeCount: 9,
        intersectionTypeCount: 2,
        conditionalTypeCount: 0,
        typeAssertionCount: 4,
        nonNullAssertionCount: 0,
        satisfiesExpressionCount: 0,
      },
      duplication: {
        duplicateBlockCount: 0,
        duplicateBlockGroupCount: 0,
        duplicateBlockGroups: [],
        duplicateLineCount: 0,
        duplicationRatio: 0,
        maxDuplicateBlockSize: 0,
      },
      halstead: {
        distinctOperators: 25,
        distinctOperands: 197,
        totalOperators: 286,
        totalOperands: 551,
        vocabulary: 222,
        length: 837,
        volume: 6523.9261,
        difficulty: 34.9619,
        effort: 228_089.04,
        time: 12_671.6133,
        bugs: 2.1746,
      },
      maintainabilityIndex: 11.6879,
    },
    oracleFunctions: [
      ['(anonymous)', 74, 74, 'cyclomatic', 'lizard', 1],
      ['(anonymous)', 99, 99, 'cyclomatic', 'lizard', 1],
      ['(anonymous)', 100, 100, 'cyclomatic', 'lizard', 1],
      ['(anonymous)', 101, 101, 'cyclomatic', 'lizard', 1],
      ['(anonymous)', 102, 105, 'cyclomatic', 'lizard', 1],
      ['(anonymous)', 106, 109, 'cyclomatic', 'lizard', 1],
      ['getDynamicProps', 163, 178, 'cognitive', 'sonarjs', 3],
      ['ImageElement', 181, 304, 'cyclomatic', 'lizard', 2],
      ['(anonymous)', 230, 268, 'cognitive', 'sonarjs', 12],
      ['(anonymous)', 230, 268, 'cyclomatic', 'lizard', 10],
      ['(anonymous)', 280, 290, 'cyclomatic', 'lizard', 1],
      ['(anonymous)', 291, 301, 'cognitive', 'sonarjs', 2],
      ['(anonymous)', 291, 301, 'cyclomatic', 'lizard', 3],
      ['ImagePreload', 307, 353, 'cognitive', 'sonarjs', 3],
      ['Image', 356, 415, 'cyclomatic', 'lizard', 2],
      ['(anonymous)', 362, 367, 'cognitive', 'sonarjs', 1],
      ['(anonymous)', 362, 367, 'cyclomatic', 'lizard', 3],
      ['(anonymous)', 364, 364, 'cyclomatic', 'lizard', 1],
      ['(anonymous)', 365, 365, 'cyclomatic', 'lizard', 1],
      ['(anonymous)', 372, 374, 'cyclomatic', 'lizard', 1],
      ['(anonymous)', 378, 380, 'cyclomatic', 'lizard', 1],
    ],
    knownDivergences: [
      ['handleLoading', 60, 161, 'cognitive', 'sonarjs', 3, 48],
      ['handleLoading', 60, 161, 'cyclomatic', 'lizard', 1, 4],
      ['(anonymous)', 74, 160, 'cyclomatic', 'lizard', 22, 20],
      ['getDynamicProps', 163, 178, 'cyclomatic', 'lizard', 5, 4],
      ['Image', 356, 415, 'cognitive', 'sonarjs', 1, 2],
    ],
  },
  {
    file: 'rails-7.1.2-methods.rb',
    language: 'ruby',
    aggregates: {
      lines: {
        total: 388,
        code: 127,
        comment: 229,
        blank: 32,
      },
      functionCount: 30,
      classCount: 2,
      cyclomaticComplexity: 35,
      maxCyclomaticComplexity: 8,
      cognitiveComplexity: 43,
      maxCognitiveComplexity: 10,
      nestingDepth: 2,
      ncssCount: 99,
      callGraph: {
        callCount: 111,
        uniqueCalleeCount: 54,
        internalCallCount: 12,
        internalEdgeCount: 12,
        recursiveFunctionCount: 0,
        maxFanIn: 3,
        maxFanOut: 2,
        maxCallDepth: 2,
      },
      coupling: {
        importCount: 1,
        importSourceCount: 1,
        relativeImportCount: 0,
        externalImportCount: 1,
        exportCount: 0,
      },
      module: {
        declarations: [
          {
            exported: false,
            name: 'ActiveSupport',
            startLine: 5,
          },
          {
            exported: false,
            name: 'ActiveSupport::Inflector',
            startLine: 18,
          },
        ],
        importSources: ['active_support/inflections'],
      },
      cohesion: {
        averageFunctionIdentifierOverlap: 0.0416,
        sharedIdentifierCount: 49,
        uniqueIdentifierCount: 98,
      },
      syntaxFeatures: {
        assignmentCount: 13,
        awaitExpressionCount: 0,
        loopStatementCount: 0,
        mutableBindingCount: 0,
        returnStatementCount: 3,
        throwStatementCount: 0,
        tryStatementCount: 1,
      },
      typeComplexity: {
        typeAnnotationCount: 0,
        typeAliasCount: 0,
        interfaceCount: 0,
        genericParameterCount: 0,
        unionTypeCount: 0,
        intersectionTypeCount: 0,
        conditionalTypeCount: 0,
        typeAssertionCount: 0,
        nonNullAssertionCount: 0,
        satisfiesExpressionCount: 0,
      },
      duplication: {
        duplicateBlockCount: 0,
        duplicateBlockGroupCount: 0,
        duplicateBlockGroups: [],
        duplicateLineCount: 0,
        duplicationRatio: 0,
        maxDuplicateBlockSize: 0,
      },
      halstead: {
        distinctOperators: 16,
        distinctOperands: 135,
        totalOperators: 163,
        totalOperands: 363,
        vocabulary: 151,
        length: 526,
        volume: 3807.4009,
        difficulty: 21.5111,
        effort: 81_901.4237,
        time: 4550.0791,
        bugs: 1.2691,
      },
      maintainabilityIndex: 24.3285,
    },
    oracleFunctions: [
      ['pluralize', 33, 35, 'cyclomatic', 'lizard', 1],
      ['singularize', 50, 52, 'cyclomatic', 'lizard', 1],
      ['upcase_first', 166, 168, 'cyclomatic', 'lizard', 2],
      ['downcase_first', 175, 177, 'cyclomatic', 'lizard', 2],
      ['ordinal', 334, 336, 'cyclomatic', 'lizard', 1],
      ['ordinalize', 347, 349, 'cyclomatic', 'lizard', 1],
    ],
    knownDivergences: [
      ['camelize', 70, 86, 'cyclomatic', 'lizard', 12, 5],
      ['underscore', 99, 107, 'cyclomatic', 'lizard', 6, 2],
      ['humanize', 135, 159, 'cyclomatic', 'lizard', 6, 4],
      ['safe_constantize', 315, 323, 'cyclomatic', 'lizard', 1, 8],
      ['const_regexp', 357, 367, 'cyclomatic', 'lizard', 3, 2],
      ['apply_inflections', 376, 385, 'cyclomatic', 'lizard', 4, 3],
    ],
  },
  {
    file: 'redis-7.2.3-intset.c',
    language: 'c',
    aggregates: {
      lines: {
        total: 561,
        code: 416,
        comment: 76,
        blank: 69,
      },
      functionCount: 26,
      classCount: 0,
      cyclomaticComplexity: 57,
      maxCyclomaticComplexity: 13,
      cognitiveComplexity: 87,
      maxCognitiveComplexity: 24,
      nestingDepth: 3,
      ncssCount: 380,
      callGraph: {
        callCount: 252,
        uniqueCalleeCount: 35,
        internalCallCount: 105,
        internalEdgeCount: 38,
        recursiveFunctionCount: 0,
        maxFanIn: 7,
        maxFanOut: 12,
        maxCallDepth: 5,
      },
      coupling: {
        importCount: 9,
        importSourceCount: 9,
        relativeImportCount: 4,
        externalImportCount: 5,
        exportCount: 0,
      },
      module: {
        declarations: [
          {
            exported: false,
            name: 'intsetNew',
            startLine: 98,
          },
          {
            exported: false,
            name: 'intsetAdd',
            startLine: 206,
          },
          {
            exported: false,
            name: 'intsetRemove',
            startLine: 236,
          },
          {
            exported: false,
            name: 'intsetFind',
            startLine: 256,
          },
          {
            exported: false,
            name: 'intsetRandom',
            startLine: 262,
          },
          {
            exported: false,
            name: 'intsetMax',
            startLine: 269,
          },
          {
            exported: false,
            name: 'intsetMin',
            startLine: 275,
          },
          {
            exported: false,
            name: 'intsetGet',
            startLine: 281,
          },
          {
            exported: false,
            name: 'intsetLen',
            startLine: 290,
          },
          {
            exported: false,
            name: 'intsetBlobLen',
            startLine: 295,
          },
          {
            exported: false,
            name: 'intsetValidateIntegrity',
            startLine: 302,
          },
          {
            exported: false,
            name: 'intsetTest',
            startLine: 407,
          },
        ],
        importSources: [
          'stdio.h',
          'stdlib.h',
          'string.h',
          './intset.h',
          './zmalloc.h',
          './endianconv.h',
          './redisassert.h',
          'sys/time.h',
          'time.h',
        ],
      },
      cohesion: {
        averageFunctionIdentifierOverlap: 0.1494,
        sharedIdentifierCount: 42,
        uniqueIdentifierCount: 102,
      },
      syntaxFeatures: {
        assignmentCount: 87,
        awaitExpressionCount: 0,
        loopStatementCount: 9,
        mutableBindingCount: 56,
        returnStatementCount: 37,
        throwStatementCount: 0,
        tryStatementCount: 0,
      },
      typeComplexity: {
        typeAnnotationCount: 0,
        typeAliasCount: 0,
        interfaceCount: 0,
        genericParameterCount: 0,
        unionTypeCount: 0,
        intersectionTypeCount: 0,
        conditionalTypeCount: 0,
        typeAssertionCount: 0,
        nonNullAssertionCount: 0,
        satisfiesExpressionCount: 0,
      },
      duplication: {
        duplicateBlockCount: 2,
        duplicateBlockGroupCount: 2,
        duplicateBlockGroups: [
          [
            {
              endLine: 481,
              startLine: 458,
            },
            {
              endLine: 527,
              startLine: 504,
            },
          ],
          [
            {
              endLine: 489,
              startLine: 482,
            },
            {
              endLine: 499,
              startLine: 492,
            },
          ],
        ],
        duplicateLineCount: 60,
        duplicationRatio: 0.1442,
        maxDuplicateBlockSize: 180,
      },
      halstead: {
        distinctOperators: 26,
        distinctOperands: 164,
        totalOperators: 464,
        totalOperands: 1211,
        vocabulary: 190,
        length: 1675,
        volume: 12_679.5081,
        difficulty: 95.9939,
        effort: 1_217_155.4677,
        time: 67_619.7482,
        bugs: 4.2265,
      },
      maintainabilityIndex: 6.4705,
    },
    oracleFunctions: [
      ['_intsetValueEncoding', 46, 53, 'cyclomatic', 'lizard', 5],
      ['_intsetGetEncoded', 56, 74, 'cyclomatic', 'lizard', 3],
      ['_intsetGet', 77, 79, 'cyclomatic', 'lizard', 1],
      ['_intsetSet', 82, 95, 'cyclomatic', 'lizard', 3],
      ['intsetNew', 98, 103, 'cyclomatic', 'lizard', 1],
      ['intsetResize', 106, 111, 'cyclomatic', 'lizard', 1],
      ['intsetSearch', 117, 156, 'cyclomatic', 'lizard', 13],
      ['intsetUpgradeAndAdd', 159, 182, 'cyclomatic', 'lizard', 4],
      ['intsetMoveTail', 184, 203, 'cyclomatic', 'lizard', 3],
      ['intsetAdd', 206, 233, 'cyclomatic', 'lizard', 6],
      ['intsetRemove', 236, 253, 'cyclomatic', 'lizard', 6],
      ['intsetFind', 256, 259, 'cyclomatic', 'lizard', 2],
      ['intsetRandom', 262, 266, 'cyclomatic', 'lizard', 1],
      ['intsetMax', 269, 272, 'cyclomatic', 'lizard', 1],
      ['intsetMin', 275, 277, 'cyclomatic', 'lizard', 1],
      ['intsetGet', 281, 287, 'cyclomatic', 'lizard', 2],
      ['intsetLen', 290, 292, 'cyclomatic', 'lizard', 1],
      ['intsetBlobLen', 295, 297, 'cyclomatic', 'lizard', 1],
      ['intsetValidateIntegrity', 302, 343, 'cyclomatic', 'lizard', 10],
      ['intsetRepr', 350, 355, 'cyclomatic', 'lizard', 2],
      ['error', 357, 360, 'cyclomatic', 'lizard', 1],
      ['ok', 363, 365, 'cyclomatic', 'lizard', 1],
      ['usec', 367, 371, 'cyclomatic', 'lizard', 1],
      ['createSet', 373, 387, 'cyclomatic', 'lizard', 3],
      ['checkConsistency', 389, 404, 'cyclomatic', 'lizard', 4],
      ['intsetTest', 407, 559, 'cyclomatic', 'lizard', 5],
    ],
    knownDivergences: [],
  },
  {
    file: 'requests-2.31.0-sessions.py',
    language: 'python',
    aggregates: {
      lines: {
        total: 834,
        code: 564,
        comment: 116,
        blank: 154,
      },
      functionCount: 28,
      classCount: 2,
      cyclomaticComplexity: 81,
      maxCyclomaticComplexity: 15,
      cognitiveComplexity: 94,
      maxCognitiveComplexity: 26,
      nestingDepth: 3,
      ncssCount: 294,
      callGraph: {
        callCount: 137,
        uniqueCalleeCount: 90,
        internalCallCount: 9,
        internalEdgeCount: 4,
        recursiveFunctionCount: 0,
        maxFanIn: 3,
        maxFanOut: 2,
        maxCallDepth: 2,
      },
      coupling: {
        importCount: 16,
        importSourceCount: 16,
        relativeImportCount: 11,
        externalImportCount: 5,
        exportCount: 0,
      },
      module: {
        declarations: [
          {
            exported: false,
            name: 'merge_setting',
            startLine: 61,
          },
          {
            exported: false,
            name: 'merge_hooks',
            startLine: 91,
          },
          {
            exported: false,
            name: 'SessionRedirectMixin',
            startLine: 106,
          },
          {
            exported: false,
            name: 'Session',
            startLine: 357,
          },
          {
            exported: false,
            name: 'session',
            startLine: 821,
          },
        ],
        importSources: [
          'os',
          'sys',
          'time',
          'collections',
          'datetime',
          '._internal_utils',
          '._internal_utils.to_native_string',
          '.adapters',
          '.adapters.HTTPAdapter',
          '.auth',
          '.auth._basic_auth_str',
          '.compat',
          '.compat.Mapping',
          '.compat.cookielib',
          '.compat.urljoin',
          '.compat.urlparse',
          '.cookies',
          '.cookies.RequestsCookieJar',
          '.cookies.cookiejar_from_dict',
          '.cookies.extract_cookies_to_jar',
          '.cookies.merge_cookies',
          '.exceptions',
          '.exceptions.ChunkedEncodingError',
          '.exceptions.ContentDecodingError',
          '.exceptions.InvalidSchema',
          '.exceptions.TooManyRedirects',
          '.hooks',
          '.hooks.default_hooks',
          '.hooks.dispatch_hook',
          '.models',
          '.models.DEFAULT_REDIRECT_LIMIT',
          '.models.REDIRECT_STATI',
          '.models.PreparedRequest',
          '.models.Request',
          '.status_codes',
          '.status_codes.codes',
          '.structures',
          '.structures.CaseInsensitiveDict',
          '.utils',
          '.utils.DEFAULT_PORTS',
          '.utils.default_headers',
          '.utils.get_auth_from_url',
          '.utils.get_environ_proxies',
          '.utils.get_netrc_auth',
          '.utils.requote_uri',
          '.utils.resolve_proxies',
          '.utils.rewind_body',
          '.utils.should_bypass_proxies',
          '.utils.to_key_val_list',
        ],
      },
      cohesion: {
        averageFunctionIdentifierOverlap: 0.0994,
        sharedIdentifierCount: 73,
        uniqueIdentifierCount: 190,
      },
      syntaxFeatures: {
        assignmentCount: 99,
        awaitExpressionCount: 0,
        loopStatementCount: 9,
        mutableBindingCount: 0,
        returnStatementCount: 29,
        throwStatementCount: 3,
        tryStatementCount: 3,
      },
      typeComplexity: {
        typeAnnotationCount: 0,
        typeAliasCount: 0,
        interfaceCount: 0,
        genericParameterCount: 0,
        unionTypeCount: 0,
        intersectionTypeCount: 0,
        conditionalTypeCount: 0,
        typeAssertionCount: 0,
        nonNullAssertionCount: 0,
        satisfiesExpressionCount: 0,
      },
      duplication: {
        duplicateBlockCount: 0,
        duplicateBlockGroupCount: 0,
        duplicateBlockGroups: [],
        duplicateLineCount: 0,
        duplicationRatio: 0,
        maxDuplicateBlockSize: 0,
      },
      halstead: {
        distinctOperators: 17,
        distinctOperands: 266,
        totalOperators: 521,
        totalOperands: 1135,
        vocabulary: 283,
        length: 1656,
        volume: 13_487.5541,
        difficulty: 36.2688,
        effort: 489_177.3598,
        time: 27_176.52,
        bugs: 4.4959,
      },
      maintainabilityIndex: 0.1711,
    },
    oracleFunctions: [
      ['merge_hooks', 91, 103, 'cognitive', 'complexipy', 4],
      ['merge_hooks', 91, 103, 'cyclomatic', 'lizard', 5],
      ['get_redirect_target', 107, 125, 'cognitive', 'complexipy', 1],
      ['get_redirect_target', 107, 125, 'cyclomatic', 'lizard', 2],
      ['should_strip_auth', 127, 157, 'cognitive', 'complexipy', 6],
      ['should_strip_auth', 127, 157, 'cyclomatic', 'lizard', 10],
      ['resolve_redirects', 159, 281, 'cognitive', 'complexipy', 26],
      ['resolve_redirects', 159, 281, 'cyclomatic', 'lizard', 15],
      ['rebuild_auth', 283, 301, 'cognitive', 'complexipy', 4],
      ['rebuild_auth', 283, 301, 'cyclomatic', 'lizard', 5],
      ['rebuild_proxies', 303, 332, 'cognitive', 'complexipy', 4],
      ['rebuild_proxies', 303, 332, 'cyclomatic', 'lizard', 6],
      ['rebuild_method', 334, 354, 'cognitive', 'complexipy', 6],
      ['rebuild_method', 334, 354, 'cyclomatic', 'lizard', 7],
      ['__init__', 391, 451, 'cognitive', 'complexipy', 0],
      ['__init__', 391, 451, 'cyclomatic', 'lizard', 1],
      ['__enter__', 453, 454, 'cognitive', 'complexipy', 0],
      ['__enter__', 453, 454, 'cyclomatic', 'lizard', 1],
      ['__exit__', 456, 457, 'cognitive', 'complexipy', 0],
      ['__exit__', 456, 457, 'cyclomatic', 'lizard', 1],
      ['prepare_request', 459, 500, 'cognitive', 'complexipy', 4],
      ['prepare_request', 459, 500, 'cyclomatic', 'lizard', 6],
      ['request', 502, 591, 'cyclomatic', 'lizard', 4],
      ['get', 593, 602, 'cognitive', 'complexipy', 0],
      ['get', 593, 602, 'cyclomatic', 'lizard', 1],
      ['options', 604, 613, 'cognitive', 'complexipy', 0],
      ['options', 604, 613, 'cyclomatic', 'lizard', 1],
      ['head', 615, 624, 'cognitive', 'complexipy', 0],
      ['head', 615, 624, 'cyclomatic', 'lizard', 1],
      ['post', 626, 637, 'cognitive', 'complexipy', 0],
      ['post', 626, 637, 'cyclomatic', 'lizard', 1],
      ['put', 639, 649, 'cognitive', 'complexipy', 0],
      ['put', 639, 649, 'cyclomatic', 'lizard', 1],
      ['patch', 651, 661, 'cognitive', 'complexipy', 0],
      ['patch', 651, 661, 'cyclomatic', 'lizard', 1],
      ['delete', 663, 671, 'cognitive', 'complexipy', 0],
      ['delete', 663, 671, 'cyclomatic', 'lizard', 1],
      ['merge_environment_settings', 751, 780, 'cognitive', 'complexipy', 9],
      ['merge_environment_settings', 751, 780, 'cyclomatic', 'lizard', 8],
      ['get_adapter', 782, 794, 'cognitive', 'complexipy', 3],
      ['get_adapter', 782, 794, 'cyclomatic', 'lizard', 3],
      ['close', 796, 799, 'cognitive', 'complexipy', 1],
      ['close', 796, 799, 'cyclomatic', 'lizard', 2],
      ['__setstate__', 816, 818, 'cognitive', 'complexipy', 1],
      ['__setstate__', 816, 818, 'cyclomatic', 'lizard', 2],
      ['session', 821, 833, 'cognitive', 'complexipy', 0],
      ['session', 821, 833, 'cyclomatic', 'lizard', 1],
    ],
    knownDivergences: [
      ['merge_setting', 61, 88, 'cognitive', 'complexipy', 7, 6],
      ['merge_setting', 61, 88, 'cyclomatic', 'lizard', 8, 7],
      ['request', 502, 591, 'cognitive', 'complexipy', 1, 3],
      ['send', 673, 749, 'cognitive', 'complexipy', 14, 12],
      ['send', 673, 749, 'cyclomatic', 'lizard', 11, 10],
      ['mount', 801, 810, 'cognitive', 'complexipy', 3, 2],
      ['mount', 801, 810, 'cyclomatic', 'lizard', 4, 3],
      ['__getstate__', 812, 814, 'cognitive', 'complexipy', 1, 0],
      ['__getstate__', 812, 814, 'cyclomatic', 'lizard', 2, 1],
    ],
  },
  {
    file: 'ripgrep-14.1.0-gitignore.rs',
    language: 'rust',
    aggregates: {
      lines: {
        total: 817,
        code: 562,
        comment: 193,
        blank: 62,
      },
      functionCount: 64,
      classCount: 3,
      cyclomaticComplexity: 60,
      maxCyclomaticComplexity: 14,
      cognitiveComplexity: 69,
      maxCognitiveComplexity: 18,
      nestingDepth: 3,
      ncssCount: 360,
      callGraph: {
        callCount: 265,
        uniqueCalleeCount: 94,
        internalCallCount: 67,
        internalEdgeCount: 63,
        recursiveFunctionCount: 7,
        maxFanIn: 7,
        maxFanOut: 6,
        maxCallDepth: 5,
      },
      coupling: {
        importCount: 7,
        importSourceCount: 15,
        relativeImportCount: 7,
        externalImportCount: 8,
        exportCount: 25,
      },
      module: {
        declarations: [
          {
            exported: true,
            name: 'Glob',
            startLine: 32,
          },
          {
            exported: true,
            name: 'Gitignore',
            startLine: 81,
          },
          {
            exported: true,
            name: 'GitignoreBuilder',
            startLine: 306,
          },
          {
            exported: true,
            name: 'gitconfig_excludes_path',
            startLine: 537,
          },
          {
            exported: false,
            name: 'gitconfig_home_contents',
            startLine: 555,
          },
          {
            exported: false,
            name: 'gitconfig_xdg_contents',
            startLine: 570,
          },
          {
            exported: false,
            name: 'excludes_file_default',
            startLine: 586,
          },
          {
            exported: false,
            name: 'parse_excludes_file',
            startLine: 595,
          },
          {
            exported: false,
            name: 'expand_tilde',
            startLine: 621,
          },
          {
            exported: false,
            name: 'home_dir',
            startLine: 630,
          },
          {
            exported: false,
            name: 'tests',
            startLine: 638,
          },
        ],
        importSources: [
          'std::fs',
          'std::io',
          'std::path',
          'std::sync',
          'globset',
          'regex_automata::util::pool',
          'crate::pathutil::is_file_name',
          'crate::pathutil::strip_prefix',
          'crate::Error',
          'crate::Match',
          'crate::PartialErrorBuilder',
          'regex_automata::meta',
          'regex_automata::util',
          'super::Gitignore',
          'super::GitignoreBuilder',
        ],
      },
      cohesion: {
        averageFunctionIdentifierOverlap: 0.034,
        sharedIdentifierCount: 108,
        uniqueIdentifierCount: 180,
      },
      syntaxFeatures: {
        assignmentCount: 18,
        awaitExpressionCount: 0,
        loopStatementCount: 4,
        mutableBindingCount: 15,
        returnStatementCount: 15,
        throwStatementCount: 0,
        tryStatementCount: 0,
      },
      typeComplexity: {
        typeAnnotationCount: 0,
        typeAliasCount: 0,
        interfaceCount: 0,
        genericParameterCount: 0,
        unionTypeCount: 0,
        intersectionTypeCount: 0,
        conditionalTypeCount: 0,
        typeAssertionCount: 0,
        nonNullAssertionCount: 0,
        satisfiesExpressionCount: 0,
      },
      // Near-miss (Type-3) clone: the parse_excludes_file2/parse_excludes_file4 tests differ
      // only in where .unwrap() is applied.
      duplication: {
        duplicateBlockCount: 1,
        duplicateBlockGroupCount: 1,
        duplicateBlockGroups: [
          [
            { startLine: 763, endLine: 767 },
            { startLine: 776, endLine: 783 },
          ],
        ],
        duplicateLineCount: 13,
        duplicationRatio: 0.0231,
        maxDuplicateBlockSize: 41,
      },
      halstead: {
        distinctOperators: 23,
        distinctOperands: 388,
        totalOperators: 799,
        totalOperands: 1548,
        vocabulary: 411,
        length: 2347,
        volume: 20_378.9883,
        difficulty: 45.8814,
        effort: 935_017.3956,
        time: 51_945.4109,
        bugs: 6.793,
      },
      maintainabilityIndex: 1.7742,
    },
    oracleFunctions: [
      ['from', 47, 49, 'cyclomatic', 'lizard', 1],
      ['original', 52, 54, 'cyclomatic', 'lizard', 1],
      ['actual', 58, 60, 'cyclomatic', 'lizard', 1],
      ['is_whitelist', 63, 65, 'cyclomatic', 'lizard', 1],
      ['is_only_dir', 68, 70, 'cyclomatic', 'lizard', 1],
      ['has_doublestar_prefix', 73, 75, 'cyclomatic', 'lizard', 2],
      ['global', 130, 132, 'cyclomatic', 'lizard', 1],
      ['empty', 137, 146, 'cyclomatic', 'lizard', 1],
      ['path', 151, 153, 'cyclomatic', 'lizard', 1],
      ['is_empty', 157, 159, 'cyclomatic', 'lizard', 1],
      ['len', 163, 165, 'cyclomatic', 'lizard', 1],
      ['num_ignores', 168, 170, 'cyclomatic', 'lizard', 1],
      ['num_whitelists', 173, 175, 'cyclomatic', 'lizard', 1],
      ['matched', 188, 197, 'cyclomatic', 'lizard', 2],
      ['matched_stripped', 245, 268, 'cyclomatic', 'lizard', 6],
      ['new', 320, 328, 'cyclomatic', 'lizard', 1],
      ['case_insensitive', 523, 531, 'cyclomatic', 'lizard', 1],
      ['home_dir', 630, 635, 'cyclomatic', 'lizard', 1],
      ['gi_from_str', 643, 647, 'cyclomatic', 'lizard', 1],
      ['bytes', 747, 749, 'cyclomatic', 'lizard', 1],
      ['path_string', 751, 753, 'cyclomatic', 'lizard', 1],
      ['parse_excludes_file1', 756, 760, 'cyclomatic', 'lizard', 1],
      ['parse_excludes_file2', 763, 767, 'cyclomatic', 'lizard', 1],
      ['parse_excludes_file3', 770, 773, 'cyclomatic', 'lizard', 1],
      ['parse_excludes_file4', 776, 783, 'cyclomatic', 'lizard', 1],
      ['parse_excludes_file5', 786, 789, 'cyclomatic', 'lizard', 1],
      ['regression_106', 793, 795, 'cyclomatic', 'lizard', 1],
      ['case_insensitive', 798, 810, 'cyclomatic', 'lizard', 1],
    ],
    knownDivergences: [
      ['new', 103, 118, 'cyclomatic', 'lizard', 2, 3],
      ['matched_path_or_any_parents', 220, 242, 'cyclomatic', 'lizard', 5, 7],
      ['strip', 272, 301, 'cyclomatic', 'lizard', 7, 6],
      ['build', 333, 348, 'cyclomatic', 'lizard', 3, 1],
      ['build_global', 359, 378, 'cyclomatic', 'lizard', 4, 6],
      ['add', 387, 409, 'cyclomatic', 'lizard', 5, 7],
      ['add_str', 418, 427, 'cyclomatic', 'lizard', 3, 2],
      ['add_line', 435, 515, 'cyclomatic', 'lizard', 15, 14],
      ['gitconfig_excludes_path', 537, 551, 'cyclomatic', 'lizard', 3, 5],
      ['gitconfig_home_contents', 555, 566, 'cyclomatic', 'lizard', 3, 5],
      ['gitconfig_xdg_contents', 570, 581, 'cyclomatic', 'lizard', 4, 3],
      ['excludes_file_default', 586, 591, 'cyclomatic', 'lizard', 3, 1],
      ['parse_excludes_file', 595, 618, 'cyclomatic', 'lizard', 3, 1],
      ['expand_tilde', 621, 627, 'cyclomatic', 'lizard', 2, 3],
    ],
  },
  {
    file: 'vscode-1.85.0-uri.ts',
    language: 'typescript',
    aggregates: {
      lines: {
        total: 746,
        code: 469,
        comment: 199,
        blank: 78,
      },
      functionCount: 25,
      classCount: 4,
      cyclomaticComplexity: 157,
      maxCyclomaticComplexity: 28,
      cognitiveComplexity: 181,
      maxCognitiveComplexity: 32,
      nestingDepth: 4,
      ncssCount: 312,
      callGraph: {
        callCount: 92,
        uniqueCalleeCount: 28,
        internalCallCount: 18,
        internalEdgeCount: 14,
        recursiveFunctionCount: 1,
        maxFanIn: 3,
        maxFanOut: 3,
        maxCallDepth: 2,
      },
      coupling: {
        importCount: 4,
        importSourceCount: 4,
        relativeImportCount: 0,
        externalImportCount: 4,
        exportCount: 12,
      },
      module: {
        declarations: [
          {
            exported: false,
            name: '_schemePattern',
            startLine: 11,
          },
          {
            exported: false,
            name: '_singleSlashStart',
            startLine: 12,
          },
          {
            exported: false,
            name: '_doubleSlashStart',
            startLine: 13,
          },
          {
            exported: false,
            name: '_validateUri',
            startLine: 15,
          },
          {
            exported: false,
            name: '_schemeFix',
            startLine: 50,
          },
          {
            exported: false,
            name: '_referenceResolution',
            startLine: 58,
          },
          {
            exported: false,
            name: '_empty',
            startLine: 78,
          },
          {
            exported: false,
            name: '_slash',
            startLine: 79,
          },
          {
            exported: false,
            name: '_regexp',
            startLine: 80,
          },
          {
            exported: true,
            name: 'URI',
            startLine: 98,
          },
          {
            exported: true,
            name: 'UriComponents',
            startLine: 418,
          },
          {
            exported: true,
            name: 'isUriComponents',
            startLine: 426,
          },
          {
            exported: false,
            name: 'UriState',
            startLine: 437,
          },
          {
            exported: false,
            name: '_pathSepMarker',
            startLine: 444,
          },
          {
            exported: false,
            name: 'Uri',
            startLine: 447,
          },
          {
            exported: false,
            name: 'encodeTable',
            startLine: 508,
          },
          {
            exported: false,
            name: 'encodeURIComponentFast',
            startLine: 532,
          },
          {
            exported: false,
            name: 'encodeURIComponentMinimal',
            startLine: 596,
          },
          {
            exported: true,
            name: 'uriToFsPath',
            startLine: 617,
          },
          {
            exported: false,
            name: '_asFormatted',
            startLine: 647,
          },
          {
            exported: false,
            name: 'decodeURIComponentGraceful',
            startLine: 719,
          },
          {
            exported: false,
            name: '_rEncodedAsHex',
            startLine: 731,
          },
          {
            exported: false,
            name: 'percentDecode',
            startLine: 733,
          },
          {
            exported: true,
            name: 'UriDto',
            startLine: 743,
          },
        ],
        importSources: [
          'vs/base/common/charCode',
          'vs/base/common/marshallingIds',
          'vs/base/common/path',
          'vs/base/common/platform',
        ],
      },
      cohesion: {
        averageFunctionIdentifierOverlap: 0.0717,
        sharedIdentifierCount: 57,
        uniqueIdentifierCount: 109,
      },
      syntaxFeatures: {
        assignmentCount: 83,
        awaitExpressionCount: 0,
        loopStatementCount: 2,
        mutableBindingCount: 12,
        returnStatementCount: 35,
        throwStatementCount: 5,
        tryStatementCount: 1,
      },
      typeComplexity: {
        typeAnnotationCount: 99,
        typeAliasCount: 1,
        interfaceCount: 2,
        genericParameterCount: 1,
        unionTypeCount: 26,
        intersectionTypeCount: 0,
        conditionalTypeCount: 1,
        typeAssertionCount: 21,
        nonNullAssertionCount: 0,
        satisfiesExpressionCount: 0,
      },
      duplication: {
        duplicateBlockCount: 0,
        duplicateBlockGroupCount: 0,
        duplicateBlockGroups: [],
        duplicateLineCount: 0,
        duplicationRatio: 0,
        maxDuplicateBlockSize: 0,
      },
      halstead: {
        distinctOperators: 30,
        distinctOperands: 193,
        totalOperators: 706,
        totalOperands: 1233,
        vocabulary: 223,
        length: 1939,
        volume: 15_125.9449,
        difficulty: 95.829,
        effort: 1_449_504.4095,
        time: 80_528.0228,
        bugs: 5.042,
      },
      maintainabilityIndex: 0,
    },
    oracleFunctions: [
      ['_validateUri', 15, 44, 'cognitive', 'sonarjs', 14],
      ['_validateUri', 15, 44, 'cyclomatic', 'lizard', 9],
      ['_schemeFix', 50, 55, 'cognitive', 'sonarjs', 2],
      ['_schemeFix', 50, 55, 'cyclomatic', 'lizard', 3],
      ['_referenceResolution', 58, 76, 'cognitive', 'sonarjs', 4],
      ['_referenceResolution', 58, 76, 'cyclomatic', 'lizard', 6],
      ['isUri', 100, 115, 'cognitive', 'sonarjs', 3],
      ['isUri', 100, 115, 'cyclomatic', 'lizard', 10],
      ['constructor', 157, 177, 'cognitive', 'sonarjs', 11],
      ['constructor', 157, 177, 'cyclomatic', 'lizard', 11],
      ['fsPath', 205, 210, 'cyclomatic', 'lizard', 1],
      ['with', 214, 257, 'cognitive', 'sonarjs', 13],
      ['with', 214, 257, 'cyclomatic', 'lizard', 17],
      ['parse', 267, 280, 'cognitive', 'sonarjs', 6],
      ['parse', 267, 280, 'cyclomatic', 'lizard', 7],
      ['file', 303, 328, 'cognitive', 'sonarjs', 7],
      ['file', 303, 328, 'cyclomatic', 'lizard', 6],
      ['from', 337, 347, 'cyclomatic', 'lizard', 1],
      ['joinPath', 356, 367, 'cognitive', 'sonarjs', 4],
      ['joinPath', 356, 367, 'cyclomatic', 'lizard', 4],
      ['toString', 382, 384, 'cyclomatic', 'lizard', 1],
      ['toJSON', 386, 388, 'cyclomatic', 'lizard', 1],
      ['isUriComponents', 426, 435, 'cyclomatic', 'lizard', 11],
      ['fsPath', 452, 457, 'cognitive', 'sonarjs', 1],
      ['fsPath', 452, 457, 'cyclomatic', 'lizard', 2],
      ['toString', 459, 469, 'cognitive', 'sonarjs', 4],
      ['toString', 459, 469, 'cyclomatic', 'lizard', 3],
      ['toJSON', 471, 504, 'cognitive', 'sonarjs', 7],
      ['toJSON', 471, 504, 'cyclomatic', 'lizard', 8],
      ['encodeURIComponentFast', 532, 594, 'cyclomatic', 'lizard', 28],
      ['encodeURIComponentMinimal', 596, 612, 'cognitive', 'sonarjs', 12],
      ['encodeURIComponentMinimal', 596, 612, 'cyclomatic', 'lizard', 7],
      ['_asFormatted', 647, 715, 'cognitive', 'sonarjs', 32],
      ['_asFormatted', 647, 715, 'cyclomatic', 'lizard', 22],
      ['decodeURIComponentGraceful', 719, 729, 'cognitive', 'sonarjs', 4],
      ['decodeURIComponentGraceful', 719, 729, 'cyclomatic', 'lizard', 3],
      ['percentDecode', 733, 738, 'cognitive', 'sonarjs', 1],
      ['percentDecode', 733, 738, 'cyclomatic', 'lizard', 2],
      ['(anonymous)', 737, 737, 'cyclomatic', 'lizard', 1],
    ],
    knownDivergences: [
      ['revive', 404, 415, 'cognitive', 'sonarjs', 7, 5],
      ['revive', 404, 415, 'cyclomatic', 'lizard', 8, 4],
      ['isUriComponents', 426, 435, 'cognitive', 'sonarjs', 10, 7],
      ['encodeURIComponentFast', 532, 594, 'cognitive', 'sonarjs', 36, 31],
      ['uriToFsPath', 617, 642, 'cognitive', 'sonarjs', 11, 12],
    ],
  },
];
